### ISSUE TITLE
Node shuts down after starting

### ISSUE THREAD

**Issue by ajdevy** [zold-io/zold#163]
command to start node :

```
  /usr/local/bin/zold node --trace --verbose --invoice=dd3db33775ae3db3 --host=46.23.36.72 --dir=/home/n0n3/
```

Log:

```
163.172.106.188:4096: 599 "Failed to open TCP connection to 163.172.106.188:4096 (Connection refused - connect(2) for "163.172.106.188" port 4096)" at "Failed to open TCP connection to 163.172.106.188:4096 (Connection refused - connect(2) for "163.172.106.188" port 4096)
/usr/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
	/usr/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
	/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	/usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	/usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	/usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	/usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
	/usr/lib/ruby/2.3.0/net/http.rb:1398:in `request'
	/usr/lib/ruby/2.3.0/net/http.rb:1308:in `request_get'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/http.rb:53:in `get'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:82:in `fetch_one'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:70:in `block in fetch'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:132:in `block in iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:69:in `fetch'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:61:in `block in run'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:60:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:60:in `run'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/pull.rb:41:in `run'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/node.rb:110:in `run'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/bin/zold:127:in `<top (required)>'
	/usr/local/bin/zold:23:in `load'
	/usr/local/bin/zold:23:in `<main>'"
/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:66:in `assert_code'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:84:in `fetch_one'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:70:in `block in fetch'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:132:in `block in iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `iterate'
46.23.36.72:4096: 599 "Failed to open TCP connection to 46.23.36.72:4096 (Connection refused - connect(2) for "46.23.36.72" port 4096)" at "Failed to open TCP connection to 46.23.36.72:4096 (Connection refused - connect(2) for "46.23.36.72" port 4096)
/usr/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
	/usr/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
	/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	/usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	/usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	/usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	/usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
	/usr/lib/ruby/2.3.0/net/http.rb:1398:in `request'
	/usr/lib/ruby/2.3.0/net/http.rb:1308:in `request_get'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/http.rb:53:in `get'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:82:in `fetch_one'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:70:in `block in fetch'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:132:in `block in iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:69:in `fetch'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:61:in `block in run'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:60:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:60:in `run'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/pull.rb:41:in `run'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/node.rb:110:in `run'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/bin/zold:127:in `<top (required)>'
	/usr/local/bin/zold:23:in `load'
	/usr/local/bin/zold:23:in `<main>'"
/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:66:in `assert_code'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:84:in `fetch_one'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:70:in `block in fetch'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:132:in `block in iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `iterate'
zold.oltdaniel.tk:4096: Wallet dd3db33775ae3db3 not found
/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:83:in `fetch_one'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:70:in `block in fetch'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:132:in `block in iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:69:in `fetch'
46.38.239.39:4096: Expired score 14/6: 2018-06-05T08:58:47Z 46.38.239.39 4096 jSmv3IMH@6c50678974ee2677 a084d7 59fb8e ea1cd4 14f2a7f 31a0f63 3c0e05f 130f012 4d1156 a36a6f 240716 3dff64 9d75b7 3ea7f4 2b037f
/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:71:in `assert_valid_score'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:87:in `fetch_one'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:70:in `block in fetch'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:132:in `block in iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `iterate'
138.197.14.165:4096: Expired score 23/6: 2018-06-05T11:06:39Z 138.197.14.165 4096 H6fKHiL2@4802d8151dd9114f c99ef8 614603 aceec4 a3873b c447eb 907ceb 147be57 cd25bf 40a774 4669e6 527f66 596065 1d7df71 118c36 72f190 7aa57a a0b056 815df7 4a63dbd 41af5 1247bd b6c5a 26fd47
/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:71:in `assert_valid_score'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:87:in `fetch_one'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:70:in `block in fetch'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:132:in `block in iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `iterate'
66.70.202.35:4096: Expired score 13/6: 2018-06-05T13:23:44Z 66.70.202.35 4096 xAQ2eyiQ@2bd06ac0103ac090 cf11e 6d6ebe ab4db3 6641dd 3c9ab8 100c8c8 75c7ef 2d6203 90d7a6 67c803 1c5c5f6 82aca6 56d41d
/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:71:in `assert_valid_score'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:87:in `fetch_one'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:70:in `block in fetch'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:132:in `block in iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `iterate'
127.0.0.1:4096: 599 "Failed to open TCP connection to 127.0.0.1:4096 (Connection refused - connect(2) for "127.0.0.1" port 4096)" at "Failed to open TCP connection to 127.0.0.1:4096 (Connection refused - connect(2) for "127.0.0.1" port 4096)
/usr/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
	/usr/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
	/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	/usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	/usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	/usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	/usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
	/usr/lib/ruby/2.3.0/net/http.rb:1398:in `request'
	/usr/lib/ruby/2.3.0/net/http.rb:1308:in `request_get'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/http.rb:53:in `get'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:82:in `fetch_one'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:70:in `block in fetch'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:132:in `block in iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:69:in `fetch'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:61:in `block in run'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:60:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:60:in `run'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/pull.rb:41:in `run'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/node.rb:110:in `run'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/bin/zold:127:in `<top (required)>'
	/usr/local/bin/zold:23:in `load'
	/usr/local/bin/zold:23:in `<main>'"
/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:66:in `assert_code'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:84:in `fetch_one'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:70:in `block in fetch'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:132:in `block in iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `iterate'
138.201.231.23:4096 returned 1537b/8 of dd3db33775ae3db3 (0.10.23) in 1.43s
159.65.37.22:4096: Expired score 22/6: 2018-06-05T04:59:19Z 159.65.37.22 4096 uiCDX8eR@25d46e810279a448 1907f9b 32e1f1 dd2b7 57d16c 773d53 117b984 92cad2 188f2d 53dbc1 a5e765 5bd926 81c8e8 41dcbe eac0de 27b928b 10bb938 fc534b 122d34d 7aed51 1cae5ea 2373365 268580
/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:71:in `assert_valid_score'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:87:in `fetch_one'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:70:in `block in fetch'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:132:in `block in iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `iterate'
b1.zold.io:80: Wallet dd3db33775ae3db3 not found
/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:83:in `fetch_one'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:70:in `block in fetch'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:132:in `block in iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:69:in `fetch'
b2.zold.io:4096: Expired score 21/6: 2018-06-04T07:40:38Z b2.zold.io 4096 gldU1M1g@00000000000ff1ce 20aee1d 536302 3223a7 33175f7 108a156 1eb4dde 1aa7b11 357b7e 2a8f9b 6cbeba 599771 903655 54f5e4 145ffae 421b8 178773 6fc601 5bb1ae a28f50 1a8731 4bd152
/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:71:in `assert_valid_score'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:87:in `fetch_one'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/fetch.rb:70:in `block in fetch'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:132:in `block in iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `iterate'
1 copies of dd3db33775ae3db3 fetched, there are 1 available locally
Nothing changed in dd3db33775ae3db3 after merge of 1 copies
Expired local copies removed for dd3db33775ae3db3, 1 left
VsqhtNKT@dd3db33775ae3db3
Farm started with 4 threads at 46.23.36.72:4096
Starting up the web front at http://46.23.36.72:4096...
WEBrick 1.3.1
ruby 2.3.1 (2016-04-26) [x86_64-linux-gnu]
WEBrick::HTTPServer#start: pid=28548 port=4096
http://46.23.36.72:4096/: HTTP header X-Zold-Score is absent (HTTP_X_ZOLD_SCORE)
http://46.23.36.72:4096/remotes: HTTP header X-Zold-Score is absent (HTTP_X_ZOLD_SCORE)
37.151.236.248 - - [06/Jun/2018:19:35:31 +0300] "GET / HTTP/1.1" 200 572 6.2060
54.163.68.26 - - [06/Jun/2018:19:35:31 +0300] "GET /remotes HTTP/1.1" 200 1876 2.8041
http://46.23.36.72:4096/remotes: HTTP header X-Zold-Score is absent (HTTP_X_ZOLD_SCORE)
http://46.23.36.72:4096/: HTTP header X-Zold-Score is absent (HTTP_X_ZOLD_SCORE)
54.163.68.26 - - [06/Jun/2018:19:35:35 +0300] "GET /remotes HTTP/1.1" 200 1876 1.9010
37.151.236.248 - - [06/Jun/2018:19:35:40 +0300] "GET / HTTP/1.1" 200 572 5.0068
http://46.23.36.72:4096/favicon.ico: HTTP header X-Zold-Score is absent (HTTP_X_ZOLD_SCORE)
37.151.236.248 - - [06/Jun/2018:19:35:42 +0300] "GET /favicon.ico HTTP/1.1" 302 - 0.0025
http://46.23.36.72:4096/: HTTP header X-Zold-Score is absent (HTTP_X_ZOLD_SCORE)
37.151.236.248 - - [06/Jun/2018:19:35:47 +0300] "GET / HTTP/1.1" 200 572 3.4036
http://46.23.36.72:4096/: HTTP header X-Zold-Score is absent (HTTP_X_ZOLD_SCORE)
http://46.23.36.72:4096/remotes: HTTP header X-Zold-Score is absent (HTTP_X_ZOLD_SCORE)
37.151.236.248 - - [06/Jun/2018:19:35:54 +0300] "GET / HTTP/1.1" 200 572 3.4014
54.163.68.26 - - [06/Jun/2018:19:35:55 +0300] "GET /remotes HTTP/1.1" 200 1876 0.8026
138.201.231.23:4096 already exists in the list
There are 11 remote nodes in the list
http://46.23.36.72:4096/: HTTP header X-Zold-Score is absent (HTTP_X_ZOLD_SCORE)
138.201.231.23:4096 already exists in the list
138.201.231.23 - - [06/Jun/2018:19:36:06 +0300] "GET /remotes HTTP/1.1" 200 1876 7.6113
37.151.236.248 - - [06/Jun/2018:19:36:08 +0300] "GET / HTTP/1.1" 200 572 2.9004
There are 11 remote nodes in the list
138.201.231.23 - - [06/Jun/2018:19:36:11 +0300] "GET /remotes HTTP/1.1" 200 1876 5.8075
http://46.23.36.72:4096/: HTTP header X-Zold-Score is absent (HTTP_X_ZOLD_SCORE)
163.172.106.188:4096: 599 "Failed to open TCP connection to 163.172.106.188:4096 (Connection refused - connect(2) for "163.172.106.188" port 4096)" at "Failed to open TCP connection to 163.172.106.188:4096 (Connection refused - connect(2) for "163.172.106.188" port 4096)
/usr/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
	/usr/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
	/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	/usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	/usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	/usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	/usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
	/usr/lib/ruby/2.3.0/net/http.rb:1398:in `request'
	/usr/lib/ruby/2.3.0/net/http.rb:1308:in `request_get'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/http.rb:53:in `get'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/remote.rb:142:in `block in update'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:132:in `block in iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/remote.rb:140:in `update'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/remote.rb:90:in `run'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/node.rb:126:in `block (3 levels) in run'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/node.rb:123:in `loop'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/node.rb:123:in `block (2 levels) in run'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/verbose_thread.rb:35:in `run'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/node.rb:122:in `block in run'"
/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:66:in `assert_code'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/remote.rb:143:in `block in update'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:132:in `block in iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/remotes.rb:130:in `iterate'
	/var/lib/gems/2.3.0/gems/zold-0.10.19/lib/zold/commands/remote.rb:140:in `update'
37.151.236.248 - - [06/Jun/2018:19:36:20 +0300] "GET / HTTP/1.1" 200 572 4.3021
http://46.23.36.72:4096/remotes: the score is too weak: 0/6: 2018-06-06T16:35:14Z 46.23.36.72 4096 VsqhtNKT@dd3db33775ae3db3
46.23.36.72 - - [06/Jun/2018:19:36:23 +0300] "GET /remotes HTTP/1.1" 200 1876 1.9082
http://46.23.36.72:4096/: HTTP header X-Zold-Score is absent (HTTP_X_ZOLD_SCORE)
46.23.36.72:4096: 0 (0.10.19) in 16.33s
37.151.236.248 - - [06/Jun/2018:19:36:37 +0300] "GET / HTTP/1.1" 200 572 4.3021
138.201.231.23:4096 already exists in the list
http://46.23.36.72:4096/: HTTP header X-Zold-Score is absent (HTTP_X_ZOLD_SCORE)
There are 11 remote nodes in the list
zold.oltdaniel.tk:4096: their version 0.10.23 is higher than mine 0.10.19, reboot!
ERROR: exit
going to shutdown ...
138.201.231.23 - - [06/Jun/2018:19:36:46 +0300] "GET /remotes HTTP/1.1" 200 1876 5.7147
37.151.236.248 - - [06/Jun/2018:19:36:47 +0300] "GET / HTTP/1.1" 200 572 3.7046
138.201.231.23:4096 already exists in the list
There are 11 remote nodes in the list
138.201.231.23 - - [06/Jun/2018:19:36:50 +0300] "GET /remotes HTTP/1.1" 200 1876 5.0062
WEBrick::HTTPServer#start done.
Thread farm-1 terminated
Thread farm-2 terminated
Thread farm-3 terminated
Thread farm-4 terminated
Farm stopped
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ajdevy[/z](https://www.0crat.com/u/ajdevy) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ajdevy this is an expected behavior, see fe1c117

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
