### ISSUE TITLE
runtime error in remotes.error()

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#175]
```
ERROR: RuntimeError: b1.zold.io:80 is absent /var/lib/gems/2.3.0/gems/zold-0.11.6/lib/zold/remotes.rb:148:in `error'
        /var/lib/gems/2.3.0/gems/zold-0.11.6/lib/zold/remotes.rb:139:in `rescue in block in iterate'
        /var/lib/gems/2.3.0/gems/zold-0.11.6/lib/zold/remotes.rb:136:in `block in iterate'
        /var/lib/gems/2.3.0/gems/zold-0.11.6/lib/zold/remotes.rb:135:in `each'
        /var/lib/gems/2.3.0/gems/zold-0.11.6/lib/zold/remotes.rb:135:in `iterate'
        /var/lib/gems/2.3.0/gems/zold-0.11.6/lib/zold/commands/remote.rb:150:in `update'
        /var/lib/gems/2.3.0/gems/zold-0.11.6/lib/zold/commands/remote.rb:94:in `run'
        /var/lib/gems/2.3.0/gems/zold-0.11.6/lib/zold/commands/node.rb:126:in `block (3 levels) in run'
        /var/lib/gems/2.3.0/gems/zold-0.11.6/lib/zold/commands/node.rb:123:in `loop'
        /var/lib/gems/2.3.0/gems/zold-0.11.6/lib/zold/commands/node.rb:123:in `block (2 levels) in run'
        /var/lib/gems/2.3.0/gems/zold-0.11.6/lib/zold/verbose_thread.rb:35:in `run'
        /var/lib/gems/2.3.0/gems/zold-0.11.6/lib/zold/commands/node.rb:122:in `block in run'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.7`

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.7`

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.7`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#175` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
