### ISSUE TITLE
unsupported signal SIGCONT (Windows)

### ISSUE THREAD

**Issue by Dereek69** [zold-io/zold#217]
After succesfully installing the zold gem on Windows i get this error when i try to run it
> F:\Flavio\Download\PGRM Installer\Programmi\Bitcoin\zold\rsa>zold --help
F:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sigdump-0.2.4/lib/sigdump.rb:5:in 'trap': unsupported signal SIGCONT (ArgumentError)
        from F:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sigdump-0.2.4/lib/sigdump.rb:5:in 'setup'
        from F:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sigdump-0.2.4/lib/sigdump/setup.rb:3:in '<top (required)>'
        from F:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in 'require'
        from F:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in 'require'
        from F:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/zold-0.13.15/bin/zold:28:in '<top (required)>'
        from F:/Ruby24-x64/bin/zold:23:in 'load'
        from F:/Ruby24-x64/bin/zold:23:in '\<main>'

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dereek69[/z](https://www.0crat.com/u/dereek69) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#217` is not assigned, can't get performer
