### ISSUE TITLE
undefined method `downcase' for nil:NilClass in remotes.rb

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#229]
```
undefined method `downcase' for nil:NilClass; errors=1
NoMethodError: undefined method `downcase' for nil:NilClass
/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.13.17/lib/zold/remotes.rb:128:in `block in exists?'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.13.17/lib/zold/remotes.rb:128:in `each'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.13.17/lib/zold/remotes.rb:128:in `find'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.13.17/lib/zold/remotes.rb:128:in `exists?'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.13.17/lib/zold/commands/remote.rb:201:in `block (2 levels) in update'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.13.17/lib/zold/commands/remote.rb:200:in `each'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.13.17/lib/zold/commands/remote.rb:200:in `block in update'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.13.17/lib/zold/remotes.rb:156:in `block in iterate'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.13.17/lib/zold/remotes.rb:154:in `each'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.13.17/lib/zold/remotes.rb:154:in `iterate'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.13.17/lib/zold/commands/remote.rb:180:in `update'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.13.17/lib/zold/commands/remote.rb:101:in `run'
```

**Comment by 0crat** [comment]
Job [#229](https://github.com/zold-io/zold/issues/229) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by arun1595** [comment]
@yegor256 What do you think of closing this issue as it has been fixed in https://github.com/zold-io/zold/commit/0d6af710a06da267d930674ae37729213c47266d?

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#229` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#229](https://github.com/zold-io/zold/issues/229) is now out of scope
