### ISSUE TITLE
b1.zold.io:80: false can't be coerced into Fixnum

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#239]
This is what I see in logs...

```
2018-06-15T17:45:35.072581+00:00 app[web.1]: b1.zold.io:80: false can't be coerced into Fixnum; errors=5
2018-06-15T17:45:35.072663+00:00 app[web.1]: TypeError: false can't be coerced into Fixnum
2018-06-15T17:45:35.072666+00:00 app[web.1]: /app/lib/zold/commands/fetch.rb:72:in `+'
2018-06-15T17:45:35.072668+00:00 app[web.1]: /app/lib/zold/commands/fetch.rb:72:in `block in fetch'
2018-06-15T17:45:35.072670+00:00 app[web.1]: /app/lib/zold/remotes.rb:156:in `block in iterate'
2018-06-15T17:45:35.072671+00:00 app[web.1]: /app/lib/zold/remotes.rb:154:in `each'
2018-06-15T17:45:35.072673+00:00 app[web.1]: /app/lib/zold/remotes.rb:154:in `iterate'
2018-06-15T17:45:35.072675+00:00 app[web.1]: /app/lib/zold/commands/fetch.rb:71:in `fetch'
2018-06-15T17:45:35.072677+00:00 app[web.1]: /app/lib/zold/commands/fetch.rb:62:in `block in run'
2018-06-15T17:45:35.072679+00:00 app[web.1]: /app/lib/zold/commands/fetch.rb:61:in `each'
2018-06-15T17:45:35.072681+00:00 app[web.1]: /app/lib/zold/commands/fetch.rb:61:in `run'
2018-06-15T17:45:35.072682+00:00 app[web.1]: /app/lib/zold/node/entrance.rb:131:in `push_unsafe'
2018-06-15T17:45:35.072684+00:00 app[web.1]: /app/lib/zold/node/entrance.rb:113:in `block in push_sync'
2018-06-15T17:45:35.072686+00:00 app[web.1]: /app/lib/zold/node/entrance.rb:111:in `synchronize'
2018-06-15T17:45:35.072688+00:00 app[web.1]: /app/lib/zold/node/entrance.rb:111:in `push_sync'
2018-06-15T17:45:35.072690+00:00 app[web.1]: /app/lib/zold/node/entrance.rb:78:in `block in push'
```

**Comment by 0crat** [comment]
The job [#239](https://github.com/zold-io/zold/issues/239) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1661754296); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#239` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.20`

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#241](https://github.com/zold-io/zold/issues/241) is still not solved.

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.20`

**Comment by 0crat** [comment]
The job [#239](https://github.com/zold-io/zold/issues/239) is now out of scope

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#241](https://github.com/zold-io/zold/issues/241) is solved here.
