### ISSUE TITLE
zold can't start in host mode

### ISSUE THREAD

**Issue by wholegroup** [zold-io/zold#242]
```bash
andrey@localhost:~/zold$ zold node --invoice=3e808d2b523396a2
Home directory: /home/andrey/zold
Ruby version: 2.3.1
Zold gem version: 0.13.20
Node location: 139.162.220.11:4096
b1.zold.io:80 returned 762b/0t of 3e808d2b523396a2 in 0.17s: 0 (0.13.20)
8RitZbFg@3e808d2b523396a2
ERROR: Invalid host name:  (RuntimeError)
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@wholegroup[/z](https://www.0crat.com/u/wholegroup) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@wholegroup can you please run it with `--trace` and post the result here?

**Comment by wholegroup** [comment]
@yegor256 

```bash
andrey@localhost:~/zold$ zold node --invoice=3e808d2b523396a2 --trace
Home directory: /home/andrey/zold
Ruby version: 2.3.1
Zold gem version: 0.13.20
Node location: 139.162.220.11:4096
b1.zold.io:80 returned 762b/0t of 3e808d2b523396a2 in 0.27s: 0 (0.13.20)
7KaxSAsk@3e808d2b523396a2
ERROR: Invalid host name:  (RuntimeError)
/home/andrey/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zold-0.13.20/lib/zold/score.rb:38:in `initialize'
/home/andrey/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zold-0.13.20/lib/zold/node/farm.rb:66:in `new'
/home/andrey/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zold-0.13.20/lib/zold/node/farm.rb:66:in `start'
/home/andrey/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zold-0.13.20/lib/zold/commands/node.rb:158:in `run'
/home/andrey/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zold-0.13.20/bin/zold:137:in `<top (required)>'
/home/andrey/.rbenv/versions/2.3.1/bin/zold:23:in `load'
/home/andrey/.rbenv/versions/2.3.1/bin/zold:23:in `<main>'
```

**Comment by yegor256** [comment]
@wholegroup fixed in 1b0d29c Thanks! Try version 0.13.22

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#242` is not assigned, can't get performer
