### ISSUE TITLE
NPE in remotes:128

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#253]
```
undefined method `downcase' for nil:NilClass (NoMethodError)
/var/lib/gems/2.3.0/gems/zold-0.13.17/lib/zold/remotes.rb:128:in `block in exists?'
/var/lib/gems/2.3.0/gems/zold-0.13.17/lib/zold/remotes.rb:128:in `each'
/var/lib/gems/2.3.0/gems/zold-0.13.17/lib/zold/remotes.rb:128:in `find'
/var/lib/gems/2.3.0/gems/zold-0.13.17/lib/zold/remotes.rb:128:in `exists?'
/var/lib/gems/2.3.0/gems/zold-0.13.17/lib/zold/remotes.rb:177:in `error'
/var/lib/gems/2.3.0/gems/zold-0.13.17/lib/zold/remotes.rb:158:in `rescue in block in iterate'
/var/lib/gems/2.3.0/gems/zold-0.13.17/lib/zold/remotes.rb:155:in `block in iterate'
/var/lib/gems/2.3.0/gems/zold-0.13.17/lib/zold/remotes.rb:154:in `each'
/var/lib/gems/2.3.0/gems/zold-0.13.17/lib/zold/remotes.rb:154:in `iterate'
/var/lib/gems/2.3.0/gems/zold-0.13.17/lib/zold/commands/fetch.rb:71:in `fetch'
/var/lib/gems/2.3.0/gems/zold-0.13.17/lib/zold/commands/fetch.rb:62:in `block in run'
/var/lib/gems/2.3.0/gems/zold-0.13.17/lib/zold/commands/fetch.rb:61:in `each'
/var/lib/gems/2.3.0/gems/zold-0.13.17/lib/zold/commands/fetch.rb:61:in `run'
/var/lib/gems/2.3.0/gems/zold-0.13.17/lib/zold/commands/pull.rb:41:in `run'
/var/lib/gems/2.3.0/gems/zold-0.13.17/lib/zold/commands/node.rb:153:in `run'
/var/lib/gems/2.3.0/gems/zold-0.13.17/bin/zold:137:in `<top (required)>'
/usr/local/bin/zold:23:in `load'
/usr/local/bin/zold:23:in `<main>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.30`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#253` is not assigned, can't get performer
