### ISSUE TITLE
ERROR: undefined method `error' for #<Zold::Node::WebrickLog:0x00000002ff5a58> 

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#268]
```
ERROR: undefined method `error' for #<Zold::Node::WebrickLog:0x00000002ff5a58> (NoMethodError)
/usr/lib/ruby/2.3.0/webrick/server.rb:204:in `rescue in block in start'
/usr/lib/ruby/2.3.0/webrick/server.rb:175:in `block in start'
/usr/lib/ruby/2.3.0/webrick/server.rb:33:in `start'
/usr/lib/ruby/2.3.0/webrick/server.rb:164:in `start'
/var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/handler/webrick.rb:34:in `run'
/var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1524:in `start_server'
/var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1458:in `run!'
/var/lib/gems/2.3.0/gems/zold-0.13.35/lib/zold/commands/node.rb:182:in `block (3 levels) in run'
/var/lib/gems/2.3.0/gems/zold-0.13.35/lib/zold/metronome.rb:71:in `start'
/var/lib/gems/2.3.0/gems/zold-0.13.35/lib/zold/commands/node.rb:179:in `block (2 levels) in run'
/var/lib/gems/2.3.0/gems/zold-0.13.35/lib/zold/node/farm.rb:98:in `start'
/var/lib/gems/2.3.0/gems/zold-0.13.35/lib/zold/commands/node.rb:177:in `block in run'
/var/lib/gems/2.3.0/gems/zold-0.13.35/lib/zold/node/safe_entrance.rb:47:in `block in start'
/var/lib/gems/2.3.0/gems/zold-0.13.35/lib/zold/node/async_entrance.rb:47:in `block in start'
/var/lib/gems/2.3.0/gems/zold-0.13.35/lib/zold/node/spread_entrance.rb:86:in `block in start'
/var/lib/gems/2.3.0/gems/zold-0.13.35/lib/zold/node/entrance.rb:54:in `start'
/var/lib/gems/2.3.0/gems/zold-0.13.35/lib/zold/node/spread_entrance.rb:64:in `start'
/var/lib/gems/2.3.0/gems/zold-0.13.35/lib/zold/node/async_entrance.rb:40:in `start'
/var/lib/gems/2.3.0/gems/zold-0.13.35/lib/zold/node/safe_entrance.rb:47:in `start'
/var/lib/gems/2.3.0/gems/zold-0.13.35/lib/zold/commands/node.rb:174:in `run'
/var/lib/gems/2.3.0/gems/zold-0.13.35/bin/zold:142:in `<top (required)>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.37`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.37`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#268` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
