### ISSUE TITLE
RuntimeError: Invalid version name '1'

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#272]
```
RuntimeError: Invalid version name '1'
	/app/lib/zold/wallet.rb:67:in `version'
	/app/lib/zold/node/front.rb:180:in `block in <class:Front>'
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@9509281b-b1e7-4a9b-8fd0-53540a3705c3, thread: pool-88-thread-1
java.util.concurrent.ThreadPoolExecutor$AbortPolicy[2063] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@1403a549 rejected from java.util.concurrent.ThreadPoolExecutor@343ea39[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 34868]
```

[0.22.26](https://github.com/zerocracy/farm): Issue: zold-io/zold#272, Action: `opened`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.43`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@156eb3b6-83b4-4f22-8c14-0c4191b968e8, thread: pool-18-thread-1
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: 3051362d2ba0/7min/0/0/false/false by zerocrat_bot Telegram Executor
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: 3051362d2ba0/7min/0/0/false/false by zerocrat_bot Telegram Executor
```

[0.22.27](https://github.com/zerocracy/farm): Issue: zold-io/zold#272, Action: `created`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.43`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@9f6c64e7-3621-4c53-a7db-c4ce7a5cf502, thread: AsyncFlush-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "blanks/yegor256.xml" in "PMO" in 2min: 57e5019db0b7/19min/0/0/false/false by zerocrat_bot Telegram Executor
```

[0.22.28](https://github.com/zerocracy/farm): CID: [1721421004](https://www.0crat.com/CAZPZR9FS/1721421004), Type: "Close job", Author: "yegor256"

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#272` is not assigned, can't get performer
