### ISSUE TITLE
no implicit conversion of Zold::Amount into String

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#278]
```
TypeError: no implicit conversion of Zold::Amount into String
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.13.45/lib/zold/node/front.rb:187:in `+'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.13.45/lib/zold/node/front.rb:187:in `block in <class:Front>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.46`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#278` is not assigned, can't get performer
