### ISSUE TITLE
Load error after running remote reset and remote update in sequence

### ISSUE THREAD

**Issue by zeelich7** [zold-io/zold#291]
See log below:
running the commands 
`zold remote reset` and `zold remote update` in sequence resulted in the following error.
Did not manage to replicate after, the update functioned normally.
---------------------------------------------------------------
root@AlqoMN6:~# zold remote reset
root@AlqoMN6:~# zold remote update
/var/lib/gems/2.3.0/gems/zold-0.13.46/lib/zold/wallet.rb:23:in `require_relative': cannot load such file -- /var/lib/gems/2.3.0/gems/zold-0.13.46/lib/zold/key (LoadError)
        from /var/lib/gems/2.3.0/gems/zold-0.13.46/lib/zold/wallet.rb:23:in `<top (required)>'
        from /var/lib/gems/2.3.0/gems/zold-0.13.46/bin/zold:36:in `require_relative'
        from /var/lib/gems/2.3.0/gems/zold-0.13.46/bin/zold:36:in `<top (required)>'
        from /usr/local/bin/zold:23:in `load'
        from /usr/local/bin/zold:23:in `<main>'
root@AlqoMN6:~# zold remote reset
root@AlqoMN6:~# zold remote update
b2.zold.io:4096 added to the list, 2 total

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@zeelich7[/z](https://www.0crat.com/u/zeelich7) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#291](https://github.com/zold-io/zold/issues/291) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Thanks for your contribution, @zeelich7[/z](https://www.0crat.com/u/zeelich7)! If you would be a member of [the project](https://www.0crat.com/p/CAZPZR9FS), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#291](https://github.com/zold-io/zold/issues/291), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/zold/issues/291#issuecomment-403227385))

@g4s8 This is what I know about this job in [CAZPZR9FS](https://www.0crat.com/p/CAZPZR9FS), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#291](https://github.com/zold-io/zold/issues/291) is [in scope](http://www.zerocracy.com/policy.html#14) for 12days
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @zeelich7[/z](https://www.0crat.com/u/zeelich7): This user reported the ticket
    * @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CAZPZR9FS?q=%7Bjob%3A%27gh%3Azold-io%2Fzold%23291%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
The job [#291](https://github.com/zold-io/zold/issues/291) assigned to @alhadhrami[/z](https://www.0crat.com/u/alhadhrami), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1de24e61-8e6e-465c-b4be-6690921391fc); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by alhadhrami** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/291#issuecomment-475636707))

@alhadhrami The user @alhadhrami[/z](https://www.0crat.com/u/alhadhrami) resigned from [#291](https://github.com/zold-io/zold/issues/291), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @alhadhrami[/z](https://www.0crat.com/u/alhadhrami)
