### ISSUE TITLE
ArgumentError: comparison of Fixnum with true failed

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#406]
```
comparison of Fixnum with true failed in 31s; errors=6
ArgumentError: comparison of Fixnum with true failed
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.14/lib/zold/remotes.rb:113:in `<'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.14/lib/zold/remotes.rb:113:in `assert_score_value'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.14/lib/zold/commands/remote.rb:198:in `block in elect'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.14/lib/zold/remotes.rb:194:in `block (2 levels) in iterate'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.15`
