### ISSUE TITLE
NoMethodError: undefined method `in_debt?'

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#409]
```
ERROR: NoMethodError: undefined method `in_debt?' for #<Zold::Amount:0x0000000148cf78 @coins=4542064747>
/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.14/lib/zold/commands/taxes.rb:107:in `pay'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.14/lib/zold/commands/taxes.rb:93:in `block in run'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.14/lib/zold/commands/taxes.rb:92:in `each'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.14/lib/zold/commands/taxes.rb:92:in `run'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.14/lib/zold/commands/pay.rb:83:in `run'
	/app/objects/ops.rb:96:in `block in pay'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/tempfile.rb:295:in `open'
	/app/objects/ops.rb:93:in `pay'
	/app/objects/update_ops.rb:53:in `pay'
	/app/objects/latch_ops.rb:48:in `pay'
	/app/objects/versioned_ops.rb:46:in `pay'
	/app/objects/safe_ops.rb:45:in `pay'
	/app/objects/async_ops.rb:46:in `block in pay'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.16`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#409` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
