### ISSUE TITLE
test - http call fallback values

### ISSUE THREAD

**Issue by oltdaniel** [zold-io/zold#422]
Somehow, uncommenting the skip for [`test_front.rb#test_renders_wallet_pages`](https://github.com/zold-io/zold/blob/master/test/node/test_front.rb#L77) uses the port 80 for the following test urls, which should actually be different in the test cases, since the operating system choses reaming unused ports. The general port range for that is `:1000+`.

Found during the work on #214.

```ruby
#...
  # @todo #212:30min The test is skipped because it crashes
  #  sporadically. I don't know why. Let's investigate, find the
  #  cause and fix it properly: http://www.rultor.com/t/14887-396655530
  def test_renders_wallet_pages
    # skip
    FakeHome.new.run do |home|
      FakeNode.new(log: test_log).run(['--ignore-score-weakness']) do |port|
        wallet = home.create_wallet
        test_log.debug("Wallet created: #{wallet.id}")
        response = Zold::Http.new(uri: "http://localhost:#{port}/wallet/#{wallet.id}?sync=true", score: nil)
          .put(File.read(wallet.path))
        assert(['200', '304'].include?(response.code) , response.body)
        [
          "/wallet/#{wallet.id}",
          "/wallet/#{wallet.id}.txt",
          "/wallet/#{wallet.id}/balance",
          "/wallet/#{wallet.id}/key",
          "/wallet/#{wallet.id}/mtime"
        ].each do |u|
          res = Zold::Http.new(uri: u, score: nil).get
          # Error will be thrown here
          assert_equal('200', res.code, res.body)
        end
      end
    end
  end
#...
```

```
Failure:
FrontTest#test_renders_wallet_pages [test/node/test_front.rb:94]:
Errno::ECONNREFUSED: Failed to open TCP connection to :80 (Connection refused - connect(2) for nil port 80)
	/home/daniel/git/zold/lib/zold/http.rb:83:in `get'
	/home/daniel/git/zold/test/node/fake_node.rb:78:in `block in run'
	/home/daniel/git/zold/test/fake_home.rb:45:in `block in run'
	/home/daniel/git/zold/test/fake_home.rb:43:in `run'
	/home/daniel/git/zold/test/node/fake_node.rb:48:in `run'
	/home/daniel/git/zold/test/fake_home.rb:45:in `block in run'
	/home/daniel/git/zold/test/fake_home.rb:43:in `run'.
Expected: "200"
  Actual: "599"
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#422](https://github.com/zold-io/zold/issues/422) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @oltdaniel[/z](https://www.0crat.com/u/oltdaniel)

**Comment by yegor256** [comment]
@oltdaniel This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#422` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#422](https://github.com/zold-io/zold/issues/422) is now out of scope
