### ISSUE TITLE
NoMethodError: undefined method `hex' for nil:NilClass

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#426]
```
ERROR: NoMethodError: undefined method `hex' for nil:NilClass
/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.19/lib/zold/score.rb:90:in `parse_text'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.19/lib/zold/tax.rb:83:in `block in debt'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.19/lib/zold/tax.rb:80:in `map'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.19/lib/zold/tax.rb:80:in `debt'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.19/lib/zold/tax.rb:75:in `in_debt?'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.19/lib/zold/commands/pay.rb:81:in `run'
	/app/objects/ops.rb:96:in `block in pay'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/tempfile.rb:295:in `open'
	/app/objects/ops.rb:93:in `pay'
	/app/objects/update_ops.rb:53:in `pay'
	/app/objects/latch_ops.rb:48:in `pay'
	/app/objects/versioned_ops.rb:46:in `pay'
	/app/objects/safe_ops.rb:45:in `pay'
	/app/objects/async_ops.rb:46:in `block in pay'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.20`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#426` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
