### ISSUE TITLE
NoMethodError: undefined method `amount'

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#427]
```
NoMethodError: undefined method `amount' for #<Zold::Score:0x00000004104dd0>
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.20/lib/zold/tax.rb:88:in `map'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.20/lib/zold/tax.rb:88:in `debt'
	/app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.20/lib/zold/tax.rb:75:in `in_debt?'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.21`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#427` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.22`
