### ISSUE TITLE
Node not starting with ERROR: #1/sinatra can't get exclusive access to the wallet 4e1c0b133e8141a4 because of the lock at /.zoldata/locks/4e1c0b133e8141a4: #1/sinatra (RuntimeError)

### ISSUE THREAD

**Issue by stepan-romankov** [zold-io/zold#458]
Logs are below.

```
zold_1  | Home directory: /
zold_1  | Ruby version: 2.3.1
zold_1  | Zold gem version: 0.14.33
zold_1  | Zold protocol version: 2
zold_1  | Network ID: zold
zold_1  | Node location: 62.113.238.234:4096
zold_1  | Local address: http://localhost:4096/
zold_1  | Remote nodes (1): b1.zold.io:80
zold_1  | Wallets at: /
zold_1  | The wallet 4e1c0b133e8141a4 is not available locally, will pull now...
zold_1  | b1.zold.io:80/0 returned 2306b/33.89ZLD/18t/85fca9/1h/1c as copy 1 of 4e1c0b133e8141a4 in 1.36s: 0 (0.14.33)
zold_1  | 1 copies of 4e1c0b133e8141a4 fetched in 1s with the total score of 0 from 1 nodes
zold_1  | #1/sinatra still waiting for exclusive access to 4e1c0b133e8141a4, 10s already: #1/sinatra
zold_1  | #1/sinatra still waiting for exclusive access to 4e1c0b133e8141a4, 12s already: #1/sinatra
zold_1  | #1/sinatra still waiting for exclusive access to 4e1c0b133e8141a4, 14s already: #1/sinatra
zold_1  | #1/sinatra still waiting for exclusive access to 4e1c0b133e8141a4, 16s already: #1/sinatra
zold_1  | #1/sinatra still waiting for exclusive access to 4e1c0b133e8141a4, 18s already: #1/sinatra
zold_1  | #1/sinatra still waiting for exclusive access to 4e1c0b133e8141a4, 20s already: #1/sinatra
zold_1  | #1/sinatra still waiting for exclusive access to 4e1c0b133e8141a4, 22s already: #1/sinatra
zold_1  | #1/sinatra still waiting for exclusive access to 4e1c0b133e8141a4, 24s already: #1/sinatra
zold_1  | #1/sinatra still waiting for exclusive access to 4e1c0b133e8141a4, 26s already: #1/sinatra
zold_1  | #1/sinatra still waiting for exclusive access to 4e1c0b133e8141a4, 28s already: #1/sinatra
zold_1  | ERROR: #1/sinatra can't get exclusive access to the wallet 4e1c0b133e8141a4 because of the lock at /.zoldata/locks/4e1c0b133e8141a4: #1/sinatra (RuntimeError)
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@stepan-romankov[/z](https://www.0crat.com/u/stepan-romankov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.34`

**Comment by stepan-romankov** [comment]
@yegor256 I'm trying an update!

**Comment by stepan-romankov** [comment]
@yegor256 ,

This problem disappeared but I still can't get the nod up. Now with 
```
zold_1  | Home directory: /data
zold_1  | Ruby version: 2.3.1
zold_1  | Zold gem version: 0.14.34
zold_1  | Zold protocol version: 2
zold_1  | Network ID: zold
zold_1  | Node location: 62.113.238.236:4096
zold_1  | Local address: http://localhost:4096/
zold_1  | Remote nodes (1): b1.zold.io:80
zold_1  | Wallets at: /data
zold_1  | b1.zold.io:80: The wallet 4e1c0b133e8141a4 is in network 'zold', while we are in 'test' in 4s
zold_1  | ERROR: No nodes out of 1 have the wallet 4e1c0b133e8141a4 (RuntimeError)
```

**Comment by stepan-romankov** [comment]
starting node as 
```
zold node --invoice=4e1c0b133e8141a4 --threads=7 --network=zold
```
also doesn't help

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.35`

**Comment by yegor256** [comment]
@stepan-romankov please, try 0.14.35

**Comment by stepan-romankov** [comment]
Hi, @yegor256, still the same 
```
zold_1  | Home directory: /
zold_1  | Ruby version: 2.3.1
zold_1  | Zold gem version: 0.14.35
zold_1  | Zold protocol version: 2
zold_1  | Network ID: zold
zold_1  | Node location: 62.113.238.234:4096
zold_1  | Local address: http://localhost:4096/
zold_1  | Remote nodes (1): b1.zold.io:80
zold_1  | Wallets at: /
zold_1  | b1.zold.io:80: The wallet 4e1c0b133e8141a4 is in network 'zold', while we are in 'test' in 2s
zold_1  | ERROR: No nodes out of 1 have the wallet 4e1c0b133e8141a4 (RuntimeError)
zold_1  | Home directory: /
zold_1  | Ruby version: 2.3.1
zold_1  | **Zold gem version: 0.14.35**
zold_1  | Zold protocol version: 2
zold_1  | Network ID: zold
zold_1  | Node location: 62.113.238.234:4096
zold_1  | Local address: http://localhost:4096/
zold_1  | Remote nodes (1): b1.zold.io:80
zold_1  | Wallets at: /
zold_1  | b1.zold.io:80: The wallet 4e1c0b133e8141a4 is in network 'zold', while we are in 'test' in 1s
zold_1  | ERROR: No nodes out of 1 have the wallet 4e1c0b133e8141a4 (RuntimeError)
```

**Comment by stepan-romankov** [comment]
@yegor256 not too much difference
```
zold_1  | Home directory: /data
zold_1  | Ruby version: 2.3.1
zold_1  | Zold gem version: 0.14.35
zold_1  | Zold protocol version: 2
zold_1  | Network ID: zold
zold_1  | Node location: 62.113.238.236:4096
zold_1  | Local address: http://localhost:4096/
zold_1  | Remote nodes (1): b1.zold.io:80
zold_1  | Wallets at: /data
zold_1  | b1.zold.io:80: The wallet 4e1c0b133e8141a4 is in network 'zold', while we are in 'test' in 1s
zold_1  | ERROR: No nodes out of 1 have the wallet 4e1c0b133e8141a4 (RuntimeError)
zold_1  | /var/lib/gems/2.3.0/gems/zold-0.14.35/lib/zold/commands/fetch.rb:90:in `fetch'
zold_1  | /var/lib/gems/2.3.0/gems/zold-0.14.35/lib/zold/commands/fetch.rb:73:in `block in run'
zold_1  | /var/lib/gems/2.3.0/gems/zold-0.14.35/lib/zold/commands/fetch.rb:72:in `each'
zold_1  | /var/lib/gems/2.3.0/gems/zold-0.14.35/lib/zold/commands/fetch.rb:72:in `run'
zold_1  | /var/lib/gems/2.3.0/gems/zold-0.14.35/lib/zold/commands/pull.rb:44:in `run'
zold_1  | /var/lib/gems/2.3.0/gems/zold-0.14.35/lib/zold/commands/invoice.rb:64:in `invoice'
zold_1  | /var/lib/gems/2.3.0/gems/zold-0.14.35/lib/zold/commands/invoice.rb:56:in `run'
zold_1  | /var/lib/gems/2.3.0/gems/zold-0.14.35/lib/zold/commands/node.rb:201:in `run'
zold_1  | /var/lib/gems/2.3.0/gems/zold-0.14.35/bin/zold:168:in `<top (required)>'
zold_1  | /usr/local/bin/zold:23:in `load'
zold_1  | /usr/local/bin/zold:23:in `<main>'
```

**Comment by yegor256** [comment]
@stepan-romankov please, try version 0.14.36

**Comment by stepan-romankov** [comment]
@yegor256 Hi, works fine now. Issue can be closed.

**Comment by stepan-romankov** [comment]
@0crat close the issue.

**Comment by 0crat** [comment]
> @0crat close the issue. ([here](https://github.com/zold-io/zold/issues/458#issuecomment-413790620))

@stepan-romankov Can't understand "close", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by yegor256** [comment]
@stepan-romankov just close the GitHub ticket

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#458` is not assigned, can't get performer
