### ISSUE TITLE
no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#461]
```
TypeError: no implicit conversion of String into Integer
	/Volumes/ssd2/code/zold/zold/lib/zold/remotes.rb:85:in `[]'
	/Volumes/ssd2/code/zold/zold/lib/zold/remotes.rb:85:in `assert_code'
	/Volumes/ssd2/code/zold/zold/lib/zold/commands/fetch.rb:109:in `fetch_one'
	/Volumes/ssd2/code/zold/zold/lib/zold/commands/fetch.rb:86:in `block in fetch'
	/Volumes/ssd2/code/zold/zold/lib/zold/remotes.rb:192:in `block (2 levels) in iterate'
```

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#461` is not assigned, can't get performer
