### ISSUE TITLE
TestFront#test_renders_wallet_pages is not stable

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#462]
```
FrontTest#test_renders_wallet_pages:
RuntimeError: '404' is not equal to '200' even after 30s of waiting
    /home/r/repo/test/test__helper.rb:55:in `block in assert_equal_wait'
    /home/r/repo/test/test__helper.rb:47:in `loop'
    /home/r/repo/test/test__helper.rb:47:in `assert_equal_wait'
    /home/r/repo/test/node/test_front.rb:84:in `block (2 levels) in test_renders_wallet_pages'
    /home/r/repo/test/node/fake_node.rb:77:in `block in run'
    /home/r/repo/test/fake_home.rb:46:in `block in run'
    /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
    /home/r/repo/test/fake_home.rb:44:in `run'
    /home/r/repo/test/node/fake_node.rb:48:in `run'
    /home/r/repo/test/node/test_front.rb:78:in `block in test_renders_wallet_pages'
    /home/r/repo/test/fake_home.rb:46:in `block in run'
    /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
    /home/r/repo/test/fake_home.rb:44:in `run'
    /home/r/repo/test/node/test_front.rb:77:in `test_renders_wallet_pages'
```

**Comment by 0crat** [comment]
This job is not in scope
