### ISSUE TITLE
FarmTest#test_renders_in_text is not stable

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#465]
```
FarmTest#test_renders_in_text:
NoMethodError: undefined method `join' for nil:NilClass
Did you mean?  JSON
    /home/r/repo/lib/zold/node/farm.rb:60:in `block in to_text'
    /home/r/repo/lib/zold/node/farm.rb:59:in `map'
    /home/r/repo/lib/zold/node/farm.rb:59:in `to_text'
    /home/r/repo/test/node/test_farm.rb:56:in `block (2 levels) in test_renders_in_text'
    /home/r/repo/lib/zold/node/farm.rb:112:in `start'
    /home/r/repo/test/node/test_farm.rb:55:in `block in test_renders_in_text'
    /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
    /home/r/repo/test/node/test_farm.rb:53:in `test_renders_in_text'
```

**Comment by 0crat** [comment]
This job is not in scope
