### ISSUE TITLE
RuntimeError: The tax payment already exists

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#488]
```
2018-10-11T10:13:43.787536+00:00 app[web.1]: ERROR: RuntimeError: The tax payment already exists: 0739;2018-10-11T10:13:43Z;fffffffebbd3ae00;GDaprWpo;912ecc24b32dbe74;TAXES 6 5bbe5614 167.99.77.100 1000 GDaprWpo 912ecc24b32dbe74 2af2c5a ebc077 a0e3d1 3c948e 2245c4b 2bafdb 6650d9 ba0736;S7IqWzvU4vHaSI3/L+0HbCmtp8Y3BBCDyvzVyKVbVTriisaQQ37rlaE+VYdhPHnMs3XFwpR9GGcY5IjuvVq7/y1h4thmXsWsCgPpjGPphJBq1gWo2wmTqZvgt1EXXzw5NqHYC7RqE2JcroYtOABrZQ5xOHDO/CfDbFQ4LOW0R0uWCkwYbk14sg2Gp9uyEpmDPcTAns7jsDVMxh3Qc2T8I9aN2chlUUllgM2LuY46ZxiZk90P8HRn4uTvmeZdFpvEXaOt3rRDbsKmk+m+JSc4c9tuxwSgTEKt4hVo3HpV7hqTSddUbr1h8qeggo5BFNDgKAwVavdVjD3afDnOyHu4SWjHdKKJGe9rccB9J6mxVpGSM3pCcPVYLFo49bFqc1b1u7wl21ewCcNlSr9CTtQ/3Idc4pu+SMcQCemawWiHpQLgLDa+0k4l/fpVibGWXrmMrtUCZ7o6gF/+zPBOqKce0fdNKHQ42iYFkikopG9DT1GxIvUVOpvLajLNi//ownuPup9HrzlfNWcRH1Hh96dqGGvqLOWMewH6UsO/OqqUhfuz6vj8JiIZqqf2zVDkATREQCIHO2Y4cWIk/Fi3vFuRxAMjULNhVV7Z3yj1rkQpdjlzOC29Y6OY/lri8cl3avbBMcu5YvflOgghhaWTdbLir9IFlZRCvwqLVYtStYhujtM=
2018-10-11T10:13:43.787541+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.44/lib/zold/wallet.rb:136:in `add'
2018-10-11T10:13:43.787543+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.44/lib/zold/wallet.rb:127:in `sub'
2018-10-11T10:13:43.787545+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.44/lib/zold/tax.rb:71:in `pay'
2018-10-11T10:13:43.787546+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.44/lib/zold/commands/taxes.rb:121:in `pay'
2018-10-11T10:13:43.787549+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.44/lib/zold/commands/taxes.rb:98:in `block (2 levels) in run'
2018-10-11T10:13:43.787550+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.44/lib/zold/sync_wallets.rb:73:in `block (2 levels) in find'
2018-10-11T10:13:43.787552+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.44/lib/zold/sync_wallets.rb:55:in `open'
2018-10-11T10:13:43.787553+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.44/lib/zold/sync_wallets.rb:55:in `block in find'
2018-10-11T10:13:43.787555+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.44/lib/zold/wallets.rb:66:in `find'
2018-10-11T10:13:43.787557+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.44/lib/zold/sync_wallets.rb:52:in `find'
2018-10-11T10:13:43.787558+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.44/lib/zold/commands/taxes.rb:97:in `block in run'
2018-10-11T10:13:43.787560+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.44/lib/zold/commands/taxes.rb:96:in `each'
2018-10-11T10:13:43.787561+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.44/lib/zold/commands/taxes.rb:96:in `run'
2018-10-11T10:13:43.787563+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.44/lib/zold/commands/pay.rb:99:in `taxes'
2018-10-11T10:13:43.787564+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.44/lib/zold/commands/pay.rb:81:in `run'
2018-10-11T10:13:43.787566+00:00 app[web.1]: /app/objects/stress.rb:168:in `block (3 levels) in pay'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.45`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#488` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
