### ISSUE TITLE
RuntimeError: The tax payment already exists in 221255bc9af7baec

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#489]
```
2018-10-11T12:05:08.748480+00:00 app[web.1]: ERROR: RuntimeError: The tax payment already exists in 221255bc9af7baec: 073a;2018-10-11T12:05:08Z;ffffffff00000000;GDaprWpo;912ecc24b32dbe74;TAXES 6 5bbe5614 167.99.77.100 1000 GDaprWpo 912ecc24b32dbe74 2af2c5a ebc077 a0e3d1 3c948e 2245c4b 2bafdb 6650d9 ba0736;EEbxqnWRZZgpm6VH9aZUlZ7ad8/pigopIbv5Qg0Zrv1rjiN/+JOIIcGzGVuvjK/ERa9OM5G9KhJFhDgbk4A1uMjQLU0DgHZoWgJIZvMG89XrIxWj9MrEiXcELbuFZyYjSkw1LizFkHk9REPcjBZHgu1sUgMTkvxPJBPrJsFfjvlIMjinfWuaaSt0kyH4uS0qp3ta9W6+/1fKQPRbwpYFfsbVys13jI2b2vCI1k/Rza50CfOnqYKzi1kDmIefMEaEmlbKFPUyua4PvLuCLS9O2JcMNUAOQAfsqX39T4+1CXrxVnMWQ9Q9yBIDgaE+o6Ta39QpDkUkoWprz7nCEcX1eKdVWwv7zAwEtkfxW1d5R241Ecv3EQgYYxmHM4Jc39iKVrbOQmjds+zTaw8LMGyQcpOHHJT9SRmZhUB0Z+r5lF3SzlbmRep0joOycet+3DctU1Qj/a0wQbJtuainFdzi7P5trApY50YI9+2PxmOr2xttdbCsRdlQ5GfWBs43OH7FaPLlrSITnp4F0kG76fhPqYFsbyiAaALNaPM3lIZzbhXnOu6sgE9kX05/MzpykrA+Fr2wd36At9dmx+njfyACj8i6iuVikQGah+RIMke8xuM/rEt8dV1IIm1vr9kmWN5nBqKVipJMGL4CIMyAdNySI6CFwsiKSv9KH4syCUQ7sl8=
2018-10-11T12:05:08.748484+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.45/lib/zold/wallet.rb:136:in `add'
2018-10-11T12:05:08.748486+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.45/lib/zold/wallet.rb:127:in `sub'
2018-10-11T12:05:08.748488+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.45/lib/zold/tax.rb:70:in `pay'
2018-10-11T12:05:08.748490+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.45/lib/zold/commands/taxes.rb:124:in `pay'
2018-10-11T12:05:08.748492+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.45/lib/zold/commands/taxes.rb:101:in `block (2 levels) in run'
2018-10-11T12:05:08.748493+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.45/lib/zold/sync_wallets.rb:73:in `block (2 levels) in find'
2018-10-11T12:05:08.748495+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.45/lib/zold/sync_wallets.rb:55:in `open'
2018-10-11T12:05:08.748497+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.45/lib/zold/sync_wallets.rb:55:in `block in find'
2018-10-11T12:05:08.748498+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.45/lib/zold/wallets.rb:66:in `find'
2018-10-11T12:05:08.748500+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.45/lib/zold/sync_wallets.rb:52:in `find'
2018-10-11T12:05:08.748502+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.45/lib/zold/commands/taxes.rb:100:in `block in run'
2018-10-11T12:05:08.748503+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.45/lib/zold/commands/taxes.rb:99:in `each'
2018-10-11T12:05:08.748505+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.45/lib/zold/commands/taxes.rb:99:in `run'
2018-10-11T12:05:08.748506+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.45/lib/zold/commands/pay.rb:99:in `taxes'
2018-10-11T12:05:08.748508+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/zold-0.14.45/lib/zold/commands/pay.rb:81:in `run'
2018-10-11T12:05:08.748509+00:00 app[web.1]: /app/objects/stress.rb:168:in `block (3 levels) in pay'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.46`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#489` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
