### ISSUE TITLE
NPE in Metronome

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#490]
```
NoMethodError: undefined method `join' for nil:NilClass
Did you mean?  JSON
	/var/lib/gems/2.3.0/gems/zold-0.14.42/lib/zold/metronome.rb:43:in `block in to_text'
	/var/lib/gems/2.3.0/gems/zold-0.14.42/lib/zold/metronome.rb:42:in `map'
	/var/lib/gems/2.3.0/gems/zold-0.14.42/lib/zold/metronome.rb:42:in `to_text'
	/var/lib/gems/2.3.0/gems/zold-0.14.42/lib/zold/node/front.rb:367:in `block in <class:Front>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.47`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#490` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
