### ISSUE TITLE
Errno::ENOMEM: Cannot allocate memory - find

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#508]
```
Errno::ENOMEM: Cannot allocate memory - find /root/.zoldata/async-entrance  -type f -print 2>/dev/null
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.16.2/lib/zold/dir_items.rb:42:in ``'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.16.2/lib/zold/dir_items.rb:42:in `fetch'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.16.2/lib/zold/node/async_entrance.rb:134:in `queue'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.16.2/lib/zold/node/async_entrance.rb:119:in `take'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.16.2/lib/zold/node/async_entrance.rb:75:in `block (5 levels) in start'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.16.2/lib/zold/verbose_thread.rb:38:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.16.2/lib/zold/node/async_entrance.rb:75:in `block (4 levels) in start'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.16.2/lib/zold/node/async_entrance.rb:74:in `loop'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.16.2/lib/zold/node/async_entrance.rb:74:in `block (3 levels) in start'
	/usr/local/rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/usr/local/rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/usr/local/rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/usr/local/rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/usr/local/rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/usr/local/rvm/gems/ruby-2.5.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#508` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.3`

**Comment by 0crat** [comment]
Job was finished in 17 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#508](https://github.com/zold-io/zold/issues/508) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
