### ISSUE TITLE
MASTER tests failing

### ISSUE THREAD

**Issue by SergeyKutsko** [zold-io/zold#510]
```
Node at TCP port 33285 stopped!
F

Failure:
TestZold#test_all_scripts [/home/serg/projects/zold/test/test_zold.rb:54]:
distribute-wallet.sh
+ shopt -s expand_aliases
+ export RUBYOPT=-W0
+ RUBYOPT=-W0
+ alias 'zold=/home/serg/projects/zold/bin/zold --ignore-this-stupid-option --halt-code=test --ignore-global-config --trace --network=test --no-colors --dump-errors'
++ start_node
+++ reserve_port
+++ python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()'
++ port=34046
++ mkdir 34046
++ cd 34046
++ pid=12350
++ echo 12350
++ cd ..
++ wait_for_url http://localhost:34046/
++ /home/serg/projects/zold/bin/zold --ignore-this-stupid-option --halt-code=test --ignore-global-config --trace --network=test --no-colors --dump-errors node --trace --invoice=DISTRWALLET@ffffffffffffffff --host=localhost --port=34046 --bind-port=34046 --threads=0 --routine-immediately
++ i=0
++ curl --silent --fail http://localhost:34046/
++ (( i++ ))
++ sleep 0
++ (( i==30 ))
++ sleep 5
++ curl --silent --fail http://localhost:34046/
++ echo 34046
+ first=34046
++ start_node
+++ reserve_port
+++ python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()'
++ port=33285
++ mkdir 33285
++ cd 33285
++ pid=12401
++ echo 12401
++ cd ..
++ wait_for_url http://localhost:33285/
++ i=0
++ curl --silent --fail http://localhost:33285/
++ /home/serg/projects/zold/bin/zold --ignore-this-stupid-option --halt-code=test --ignore-global-config --trace --network=test --no-colors --dump-errors node --trace --invoice=DISTRWALLET@ffffffffffffffff --host=localhost --port=33285 --bind-port=33285 --threads=0 --routine-immediately
++ (( i++ ))
++ sleep 0
++ (( i==30 ))
++ sleep 5
++ curl --silent --fail http://localhost:33285/
++ echo 33285
+ second=33285
+ trap 'halt_nodes 34046 33285' EXIT
+ /home/serg/projects/zold/bin/zold --ignore-this-stupid-option --halt-code=test --ignore-global-config --trace --network=test --no-colors --dump-errors --home=34046 remote clean
+ /home/serg/projects/zold/bin/zold --ignore-this-stupid-option --halt-code=test --ignore-global-config --trace --network=test --no-colors --dump-errors --home=34046 remote add localhost 33285
localhost:33285 added to the list, 1 total
+ /home/serg/projects/zold/bin/zold --ignore-this-stupid-option --halt-code=test --ignore-global-config --trace --network=test --no-colors --dump-errors --home=33285 remote clean
+ /home/serg/projects/zold/bin/zold --ignore-this-stupid-option --halt-code=test --ignore-global-config --trace --network=test --no-colors --dump-errors --home=33285 remote add localhost 34046
ERROR: The node localhost:34046 is not responding (code is 599) (RuntimeError)
/home/serg/projects/zold/lib/zold/commands/remote.rb:181:in `add'
/home/serg/projects/zold/lib/zold/commands/remote.rb:133:in `run'
/home/serg/projects/zold/bin/zold:192:in `<main>'
+ halt_nodes 34046 33285
+ for p in '"$@"'
++ curl --silent 'http://localhost:34046/pid?halt=test'
++ echo absent
+ pid=absent
+ [[ absent =~ ^[0-9]+$ ]]
+ echo 'Node at TCP port 34046 stopped!'
Node at TCP port 34046 stopped!
+ for p in '"$@"'
++ curl --silent 'http://localhost:33285/pid?halt=test'
+ pid=12401
+ [[ 12401 =~ ^[0-9]+$ ]]
+ i=0
+ kill -0 12401
+ (( i++ ))
+ sleep 0
+ (( i==30 ))
+ echo 'Still waiting for process 12401 to die, attempt no.1'
Still waiting for process 12401 to die, attempt no.1
+ sleep 5
+ kill -0 12401
distribute-wallet.sh: line 55: kill: (12401) - No such process
+ echo 'Process 12401 is dead!'
Process 12401 is dead!
+ echo 'Node at TCP port 33285 stopped!'
Node at TCP port 33285 stopped!
.
Expected: 0
  Actual: 65280


bin/rails test home/serg/projects/zold/test/test_zold.rb:35


Interrupted. Exiting...


Finished in 228.123268s, 1.0740 runs/s, 13.9442 assertions/s.
245 runs, 3181 assertions, 1 failures, 0 errors, 7 skips

You have skipped tests. Run with --verbose for details.
rake aborted!
Command failed with status (1)
/home/serg/.rvm/gems/ruby-2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/serg/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/home/serg/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@SergeyKutsko please, use Markdown to format your reports

**Comment by yegor256** [comment]
@SergeyKutsko I can't reproduce the bug now, maybe it was a temporary problem. Now master is clean.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#510` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
