### ISSUE TITLE
TestAsyncEntrance#test_handles_broken_entrance_gracefully

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#522]
```
TestAsyncEntrance#test_handles_broken_entrance_gracefully:
RuntimeError: find: `/tmp/d20181102-29109-1vdrra7/34fc26de85af10ea': No such file or directory
    /home/travis/build/zold-io/zold/lib/zold/dir_items.rb:47:in `fetch'
    /home/travis/build/zold-io/zold/lib/zold/node/async_entrance.rb:135:in `queue'
    /home/travis/build/zold-io/zold/lib/zold/node/async_entrance.rb:110:in `push'
    /home/travis/build/zold-io/zold/test/node/test_async_entrance.rb:78:in `block (2 levels) in test_handles_broken_entrance_gracefully'
    /home/travis/build/zold-io/zold/lib/zold/node/async_entrance.rb:82:in `block in start'
    /home/travis/build/zold-io/zold/test/node/fake_entrance.rb:37:in `start'
    /home/travis/build/zold-io/zold/lib/zold/node/async_entrance.rb:64:in `start'
    /home/travis/build/zold-io/zold/test/node/test_async_entrance.rb:77:in `block in test_handles_broken_entrance_gracefully'
    /home/travis/build/zold-io/zold/test/fake_home.rb:48:in `block in run'
    /home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
    /home/travis/build/zold-io/zold/test/fake_home.rb:46:in `run'
    /home/travis/build/zold-io/zold/test/node/test_async_entrance.rb:75:in `test_handles_broken_entrance_gracefully'
```

This happens once in a while. For example, here: https://travis-ci.org/zold-io/zold/jobs/449935949 Let's try to fix.

**Comment by 0crat** [comment]
Job [#522](https://github.com/zold-io/zold/issues/522) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#522` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#522](https://github.com/zold-io/zold/issues/522) is now out of scope
