### ISSUE TITLE
NameError: uninitialized constant Zold::Front::Usagewatch on requesting host.ip.address:4096

### ISSUE THREAD

**Issue by denis-konovalyenko** [zold-io/zold#523]
```
NameError: uninitialized constant Zold::Front::Usagewatch
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.9/lib/zold/node/front.rb:193:in `block (2 levels) in <class:Front>'
	/usr/local/lib/ruby/gems/2.4/gems/zache-0.2.0/lib/zache.rb:39:in `block (2 levels) in get'
	/usr/local/lib/ruby/gems/2.4/gems/zache-0.2.0/lib/zache.rb:53:in `calc'
	/usr/local/lib/ruby/gems/2.4/gems/zache-0.2.0/lib/zache.rb:39:in `block in get'
	/usr/local/lib/ruby/gems/2.4/gems/zache-0.2.0/lib/zache.rb:38:in `synchronize'
	/usr/local/lib/ruby/gems/2.4/gems/zache-0.2.0/lib/zache.rb:38:in `get'
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.9/lib/zold/node/front.rb:193:in `block in <class:Front>'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/rack-2.0.5/lib/rack/deflater.rb:34:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/rack-protection-2.0.4/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/rack-protection-2.0.4/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/rack-protection-2.0.4/lib/rack/protection/json_csrf.rb:26:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/rack-protection-2.0.4/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/rack-2.0.5/lib/rack/null_logger.rb:9:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/usr/local/lib/ruby/gems/2.4/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/usr/local/lib/ruby/gems/2.4/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/usr/local/lib/ruby/gems/2.4/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'
	/usr/local/lib/ruby/gems/2.4/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'
```

Please contact me if more informaton is needed.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.11`

**Comment by yegor256** [comment]
@denis-konovalyenko I believe it's fixed now

**Comment by denis-konovalyenko** [comment]
> @denis-konovalyenko I believe it's fixed now

@yegor256 , many thanks for addressing the issue!

**Comment by denis-konovalyenko** [comment]
@yegor256 it looks like the issue is still reproducible.
```
NameError: uninitialized constant Zold::Front::Usagewatch
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.12/lib/zold/node/front.rb:199:in `block (2 levels) in <class:Front>'
	/usr/local/lib/ruby/gems/2.4/gems/zache-0.2.0/lib/zache.rb:39:in `block (2 levels) in get'
	/usr/local/lib/ruby/gems/2.4/gems/zache-0.2.0/lib/zache.rb:53:in `calc'
	/usr/local/lib/ruby/gems/2.4/gems/zache-0.2.0/lib/zache.rb:39:in `block in get'
	/usr/local/lib/ruby/gems/2.4/gems/zache-0.2.0/lib/zache.rb:38:in `synchronize'
	/usr/local/lib/ruby/gems/2.4/gems/zache-0.2.0/lib/zache.rb:38:in `get'
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.12/lib/zold/node/front.rb:197:in `block in <class:Front>'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/rack-2.0.5/lib/rack/deflater.rb:34:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/rack-protection-2.0.4/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/rack-protection-2.0.4/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/rack-protection-2.0.4/lib/rack/protection/json_csrf.rb:26:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/rack-protection-2.0.4/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/rack-2.0.5/lib/rack/logger.rb:15:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/rack-2.0.5/lib/rack/common_logger.rb:33:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:231:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:224:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize'
	/usr/local/lib/ruby/gems/2.4/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call'
	/usr/local/lib/ruby/gems/2.4/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/usr/local/lib/ruby/gems/2.4/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/usr/local/lib/ruby/gems/2.4/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/usr/local/lib/ruby/gems/2.4/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'
	/usr/local/lib/ruby/gems/2.4/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'
```
Feel free to see this in action on [this node](http://91.211.13.180:4096).

**Comment by denis-konovalyenko** [comment]
@yegor256 , by the way, do I have to create a new ticket or it is eligible to reopen this one?

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.15`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.15`

**Comment by yegor256** [comment]
@denis-konovalyenko please, try again, with version 0.16.15

**Comment by denis-konovalyenko** [comment]
@yegor256 , the node has been updated to 0.16.15, but the issue is still persisting. Do I need to provide more information on that?

**Comment by yegor256** [comment]
@denis-konovalyenko this is a mystery... let me investigate

**Comment by yegor256** [comment]
@denis-konovalyenko what is your operating system?

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.16`

**Comment by denis-konovalyenko** [comment]
@yegor256 my system is FreeBSD:
```
FreeBSD dmz1 11.2-RELEASE-p4 FreeBSD 11.2-RELEASE-p4 #0: Thu Sep 27 07:46:01 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  i386
```

**Comment by yegor256** [comment]
@denis-konovalyenko I believe it's fixed in 0.16.16, please try

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by denis-konovalyenko** [comment]
@yegor256 , it is working so far. Will see how it goes.

**Comment by yegor256** [comment]
@denis-konovalyenko it's stable, won't appear again, thanks for reporting!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#523` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
