### ISSUE TITLE
rb_file_s_mtime  in async_entrance

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#528]
```
ERROR: Errno::ENOENT: No such file or directory @ rb_file_s_mtime - /root/.zoldata/async-entrance/17737fee5b825835
	/var/lib/gems/2.3.0/gems/zold-0.16.12/lib/zold/node/async_entrance.rb:59:in `mtime'
	/var/lib/gems/2.3.0/gems/zold-0.16.12/lib/zold/node/async_entrance.rb:59:in `to_json'
	/var/lib/gems/2.3.0/gems/zold-0.16.12/lib/zold/node/nodup_entrance.rb:49:in `to_json'
	/var/lib/gems/2.3.0/gems/zold-0.16.12/lib/zold/node/safe_entrance.rb:53:in `to_json'
	/var/lib/gems/2.3.0/gems/zold-0.16.12/lib/zold/node/front.rb:206:in `block in <class:Front>'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/deflater.rb:34:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.4/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.4/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.4/lib/rack/protection/json_csrf.rb:26:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.4/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/null_logger.rb:9:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call'
	/var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'
	/var/lib/gems/2.3.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'
```

**Comment by 0crat** [comment]
Job [#528](https://github.com/zold-io/zold/issues/528) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#528](https://github.com/zold-io/zold/issues/528) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/944e2735-6fe2-4751-817a-44c5a545094c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.13`

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#528](https://github.com/zold-io/zold/issues/528) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
