### ISSUE TITLE
Errno::ENOMEM: Cannot allocate memory

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#531]
```
Errno::ENOMEM: Cannot allocate memory - ps ax | grep zold | wc -l
	/var/lib/gems/2.3.0/gems/zold-0.16.13/lib/zold/node/front.rb:458:in ``'
	/var/lib/gems/2.3.0/gems/zold-0.16.13/lib/zold/node/front.rb:458:in `block in processes_count'
	/var/lib/gems/2.3.0/gems/zache-0.2.0/lib/zache.rb:39:in `block (2 levels) in get'
	/var/lib/gems/2.3.0/gems/zache-0.2.0/lib/zache.rb:53:in `calc'
	/var/lib/gems/2.3.0/gems/zache-0.2.0/lib/zache.rb:39:in `block in get'
	/var/lib/gems/2.3.0/gems/zache-0.2.0/lib/zache.rb:38:in `synchronize'
	/var/lib/gems/2.3.0/gems/zache-0.2.0/lib/zache.rb:38:in `get'
	/var/lib/gems/2.3.0/gems/zold-0.16.13/lib/zold/node/front.rb:457:in `processes_count'
	/var/lib/gems/2.3.0/gems/zold-0.16.13/lib/zold/node/front.rb:188:in `block in <class:Front>'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1635:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1635:in `block in compile!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1011:in `route_eval'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1040:in `block in process_route'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1038:in `catch'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1038:in `process_route'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:990:in `block in route!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:989:in `each'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:989:in `route!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `block in invoke'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `catch'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `invoke'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1094:in `dispatch!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:924:in `block in call!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `block in invoke'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `catch'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `invoke'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:924:in `call!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:913:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/deflater.rb:34:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/json_csrf.rb:26:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/base.rb:50:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/base.rb:50:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/null_logger.rb:9:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:194:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1958:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1502:in `block in call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1729:in `synchronize'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1502:in `call'
	/var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'
	/var/lib/gems/2.3.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.14`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.14`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.14`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#531` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
