### ISSUE TITLE
ERROR: Can't detect your IP address, you have to specify it in --host (RuntimeError)

### ISSUE THREAD

**Issue by denis-konovalyenko** [zold-io/zold#532]
Do we have undocumented limitations or this has to be considered an issue?

```
#54811: /usr/local/bin/zold --verbose node --invoice=e560c4fb95684c6d
Gem location: /usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16
Home directory: /usr/home/zold
Remote nodes: 2 total
Network: zold (main net)
Time: 2018-11-06T19:43:20Z
Home directory: /usr/home/zold
Ruby version: 2.4.5
Zold gem version: 0.16.16
Zold protocol version: 2
Network ID: zold
ERROR: Can't detect your IP address, you have to specify it in --host (RuntimeError)
Nothing else left to read from #55024
Exit code of process #55024 is 65280, was alive for 2.07s: /usr/local/bin/zold --verbose node --invoice=e560c4fb95684c6d
RuntimeError: Exit code is 65280
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/commands/node.rb:300:in `block (2 levels) in nohup'
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/commands/node.rb:297:in `loop'
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/commands/node.rb:297:in `block in nohup'
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/commands/node.rb:285:in `fork'
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/commands/node.rb:285:in `nohup'
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/commands/node.rb:160:in `run'
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/bin/zold:189:in `<top (required)>'
	/usr/local/bin/zold:23:in `load'
	/usr/local/bin/zold:23:in `<main>'Started process #55026 from process 
```

**Comment by denis-konovalyenko** [comment]
@yegor256 , in my opinion, the use case of the `--host` option has to be documented better. There is nothing mentioned in the list of zold options to run with, i.e.:
```
[zold@dmz1 ~]$ zold -h
Usage: zold [options] command [arguments]
Available commands:
    remote command [options]
      Manage remote nodes
...
    score [options]
      Generate score for the given host and port
Available options:
    --home                  Home directory (default: /usr/home/zold)
    --network               The name of the network we work in (default: zold
    -h, --help              Show these instructions
    --trace                 Show full stack trace in case of a problem
    --skip-upgrades         Don't upgrade the storage
    --ignore-global-config  Don't read options from the ~/.zold file
    --no-colors             Disable colors in the ouput
    --verbose               Enable extra logging information
    -v, --version           Show current version
```
In addition, the "[How to Start a Node](https://github.com/zold-io/zold#how-to-start-a-node)" readme section does not make the situation ever clear.

**Comment by yegor256** [comment]
@denis-konovalyenko try `zold node --help`

**Comment by yegor256** [comment]
@denis-konovalyenko I made some changes, should be better now, thanks for reporting!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#532` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by ammaratef45** [comment]
@yegor256 

as @denis-konovalyenko mentioned

> In addition, the "How to Start a Node" readme section does not make the situation ever clear.

I think this shouldn't be closed until this be fixed.
