### ISSUE TITLE
RuntimeError on pulling a wallet

### ISSUE THREAD

**Issue by denis-konovalyenko** [zold-io/zold#534]
```
[zold@dmz1 ~]$ zold -v
0.16.16
[zold@dmz1 ~]$ zold pull e560c4fb95684c6d
167.99.77.100:4096: execution expired (HTTP code 599, instead of 200) in 4.02s
138.197.140.42:4096: execution expired (HTTP code 599, instead of 200) in 4.03s
159.203.19.189:4096: execution expired (HTTP code 599, instead of 200) in 4.04s
159.203.63.90:4096: execution expired (HTTP code 599, instead of 200) in 4.1s
ERROR: No nodes out of 7 have the wallet e560c4fb95684c6d (RuntimeError)
```
More details:
```
[zold@dmz1 ~]$ zold --verbose pull e560c4fb95684c6d
Gem location: /usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16
Home directory: /usr/home/zold
Remote nodes: 7 total
Network: zold (main net)
0 expired local copies removed for e560c4fb95684c6d in 45ms, 1 left:
  1: 329 e560c4fb95684c6d/0.0000/0t/5db245/418b 418b/12ms
138.197.140.42:4096: execution expired (HTTP code 599, instead of 200) in 4.06s
RuntimeError: execution expired (HTTP code 599, instead of 200)
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/remotes.rb:100:in `assert_code'
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/commands/fetch.rb:110:in `fetch_one'
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/commands/fetch.rb:86:in `block in fetch'
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/remotes.rb:200:in `block (2 levels) in iterate'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
167.99.77.100:4096: execution expired (HTTP code 599, instead of 200) in 4.06s
RuntimeError: execution expired (HTTP code 599, instead of 200)
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/remotes.rb:100:in `assert_code'
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/commands/fetch.rb:110:in `fetch_one'
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/commands/fetch.rb:86:in `block in fetch'
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/remotes.rb:200:in `block (2 levels) in iterate'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
159.203.63.90:4096: execution expired (HTTP code 599, instead of 200) in 4.07s
RuntimeError: execution expired (HTTP code 599, instead of 200)
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/remotes.rb:100:in `assert_code'
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/commands/fetch.rb:110:in `fetch_one'
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/commands/fetch.rb:86:in `block in fetch'
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/remotes.rb:200:in `block (2 levels) in iterate'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
159.203.19.189:4096: execution expired (HTTP code 599, instead of 200) in 4.07s
RuntimeError: execution expired (HTTP code 599, instead of 200)
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/remotes.rb:100:in `assert_code'
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/commands/fetch.rb:110:in `fetch_one'
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/commands/fetch.rb:86:in `block in fetch'
	/usr/local/lib/ruby/gems/2.4/gems/zold-0.16.16/lib/zold/remotes.rb:200:in `block (2 levels) in iterate'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/usr/local/lib/ruby/gems/2.4/gems/concurrent-ruby-1.1.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
ERROR: No nodes out of 7 have the wallet e560c4fb95684c6d (RuntimeError)
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by denis-konovalyenko** [comment]
@yegor256 , thanks for looking at this! My node has been running the 0.16.18 version for about 1.5  days (below you may find the relevant health page information at the time of writing) and the same problem has been spotted today:
```
[zold@dmz1 ~]$ zold pull e560c4fb95684c6d
159.203.63.90:4096: execution expired (HTTP code 599, instead of 200) in 421ms
159.203.19.189:4096: execution expired (HTTP code 599, instead of 200) in 467ms
138.197.140.42:4096: execution expired (HTTP code 599, instead of 200) in 539ms
b1.zold.io:80: execution expired (HTTP code 599, instead of 200) in 39.09s
b2.zold.io:4096: execution expired (HTTP code 599, instead of 200) in 39.11s
ERROR: No nodes out of 5 have the wallet e560c4fb95684c6d (RuntimeError)
```

```
91.211.13.180 | 4096 | 648 | ? | i386-freebsd11 | 2 | 368 | 0.00 | 1/33 | 5 | 12 | 256 | 0.16.18/2 | 378 | 18 | 16 | 0 | 1 | 36.5 |  
```
What is more, I think, the root cause of the issue is not 100% on the zold side, as I am observing some sort of improper NAT and port fowarding coexistence (for some reasons all outgoing traffic from that dmz1 host is occasionally bloked by my router unti it is rebooted). Will firstly find a way to mitigate my environment issue - closing for now.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#534` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
