### ISSUE TITLE
Error with new logging system

### ISSUE THREAD

**Issue by emilianodellacasa** [zold-io/zold#565]
Now a couple of tests are failing, probably due to the new logging system.

A sample error is:

Error:
TestZold#test_redeploy_on_upgrade:
ArgumentError: invalid byte sequence in US-ASCII
    /home/emiliano/zold/lib/zold/log.rb:67:in `gsub'
...
    /home/emiliano/zold/test/test_zold.rb:40:in `block (2 levels) in <class:TestZold>'

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@yegor256 This is the line giving the error:

`return "#{(sec * 1_000_000).round}μs" if sec < 0.001`

In particular, it's the `μ` that is not recognized for some encodings. I Think it would be better to get rid of it.

**Comment by emilianodellacasa** [comment]
@yegor256 as you prefer

**Comment by dapi** [comment]
> maybe it's better to enforce UTF-8 for all output?

It is not good. Non unicode-terminals can breaks output.

We can disable to run zold with non-unicode locale and recommend users to set locale with UTF-8 support:

```bash
export LC_ALL=C.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
```

**Comment by yegor256** [comment]
@dapi I like this idea. let's do it.

**Comment by yegor256** [comment]
@0crat assign @dapi

**Comment by 0crat** [comment]
> @0crat assign @dapi  ([here](https://github.com/zold-io/zold/issues/565#issuecomment-441956348))

@yegor256 The job [#565](https://github.com/zold-io/zold/issues/565) assigned to @dapi[/z](https://www.0crat.com/u/dapi), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/58621dc8-6408-4076-82b3-1f9a44ad7396); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @dapi[/z](https://www.0crat.com/u/dapi) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
@dapi[/z](https://www.0crat.com/u/dapi) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by dapi** [comment]
Sorry, guys. I have rethought the issue. The best way is to:

1) Don’t use unicode characters into logging messages;
2) As hot fixe replace all non-ascii symbols in terminal input with `String#encode`. Example `'фывыфв'.encode(Encoding::ASCII, invalid: :replace, undef: :replace, replace: '?’)`
