### ISSUE TITLE
NameError: undefined local variable or method `opts' for #<Zold::Remote>

### ISSUE THREAD

**Issue by dapi** [zold-io/zold#572]
Every time I run node I see such messages in console. 

May be dup of https://github.com/zold-io/zold/issues/423 ?

```bash
danil@office:~/code/zold(master)$ ./bin/zold node  --verbose --invoice=66Yodh14@1142c2d008235bbe --host=94.232.57.6
Gem location: .
Home directory: /home/danil/code/zold
Remote nodes: 6 total
Network: zold (main net)
Time: 2018-11-26T09:25:05Z; CPUs: 8
Home directory: /home/danil/code/zold
Ruby version: 2.5.1/x86_64-linux
Zold gem version: 0.0.0
Zold protocol version: 2
Network ID: zold
Node location: 94.232.57.6:4096
Local address: http://127.0.0.1:4096/
Remote nodes (6): 138.197.140.42:4096, 159.203.19.189:4096, 167.99.77.100:4096, 159.203.63.90:4096, b2.zold.io:4096, b1.zold.io:80
Wallets at: /home/danil/code/zold
4 scores pre-loaded from /home/danil/code/zold/farm, the best is: 45/6: 2018-11-25T15:29:00Z 94.232.57.6 4096 66Yodh14@1142c2d008235bbe 1faf4e 9cbc16 6c3a84 447889 e7cb32 3da2bd a00d2f c2bf21 690352 4b7166 14fb17c 5446f6 15fc67f be1154 ab8d28 dbe60c 2f3f54 1b5065 151e80f c75342 6232cc 62600c 16eaabc 354b7c 9ad6f6 5fa33e 7ad76b 487a2a 28b99b9 b3deca 832e24 1c3e8f1 2433bf 1275a7 1677ba bd6cef 1382ad7 2141e0 ceb473 80290 10bb8f7 1610f6 574579 216a04c 1673bbc
Farm started with 5 threads (one for cleanup) at 94.232.57.6:4096, strength is 6
Added Zold::Routines::Reconnect to the metronome
Metronome started (use --no-metronome to disable it)
Starting up the web front at http://94.232.57.6:4096...
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on 0.0.0.0:4096, CTRL+C to stop
Scoring started in proc #18005 for 45/6 at 94.232.57.6:4096
Scoring started in proc #18011 for 36/6 at 94.232.57.6:4096
Scoring started in proc #18017 for 21/6 at 94.232.57.6:4096
Scoring started in proc #18023 for 13/6 at 94.232.57.6:4096


Routine Zold::Routines::Reconnect #0 failed in 1m
NameError: undefined local variable or method `opts' for #<Zold::Remote:0x000055b3b273eab8>
        /home/danil/code/zold/lib/zold/commands/remote.rb:180:in `block in defaults'
        /home/danil/code/zold/lib/zold/remotes.rb:148:in `block in defaults'
        /home/danil/code/zold/lib/zold/remotes.rb:146:in `each'
        /home/danil/code/zold/lib/zold/remotes.rb:146:in `defaults'
        /home/danil/code/zold/lib/zold/commands/remote.rb:179:in `defaults'
        /home/danil/code/zold/lib/zold/commands/remote.rb:140:in `run'
        /home/danil/code/zold/lib/zold/commands/thread_badge.rb:41:in `run'
        /home/danil/code/zold/lib/zold/commands/routines/reconnect.rb:49:in `exec'
        /home/danil/code/zold/lib/zold/metronome.rb:74:in `block (2 levels) in start'


Routine Zold::Routines::Reconnect #1 failed in 1m
NameError: undefined local variable or method `opts' for #<Zold::Remote:0x000055b3b22ba3c0>
        /home/danil/code/zold/lib/zold/commands/remote.rb:180:in `block in defaults'
        /home/danil/code/zold/lib/zold/remotes.rb:148:in `block in defaults'
        /home/danil/code/zold/lib/zold/remotes.rb:146:in `each'
        /home/danil/code/zold/lib/zold/remotes.rb:146:in `defaults'
        /home/danil/code/zold/lib/zold/commands/remote.rb:179:in `defaults'
        /home/danil/code/zold/lib/zold/commands/remote.rb:140:in `run'
        /home/danil/code/zold/lib/zold/commands/thread_badge.rb:41:in `run'
        /home/danil/code/zold/lib/zold/commands/routines/reconnect.rb:49:in `exec'
        /home/danil/code/zold/lib/zold/metronome.rb:74:in `block (2 levels) in start’
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dapi[/z](https://www.0crat.com/u/dapi) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job [#572](https://github.com/zold-io/zold/issues/572) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/cdeae38d-dc1c-4290-96f6-3c17bde32bb3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#572` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dapi[/z](https://www.0crat.com/u/dapi)

**Comment by yegor256** [comment]
@dapi fixed, thanks

**Comment by 0crat** [comment]
Job was finished in 13 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#572](https://github.com/zold-io/zold/issues/572) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
