### ISSUE TITLE
Errno::ENOMEM: Cannot allocate memory - fork(2)

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#590]
We are still in the memory leakage problem (tried to fix it in #548 and #558)

```
Errno::ENOMEM: Cannot allocate memory - fork(2)
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.17.1/lib/zold/node/farmers.rb:127:in `fork'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.17.1/lib/zold/node/farmers.rb:127:in `up'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.17.1/lib/zold/node/farm.rb:189:in `cycle'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.17.1/lib/zold/node/farm.rb:127:in `block (3 levels) in start'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.17.1/lib/zold/endless.rb:46:in `block (2 levels) in run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.17.1/lib/zold/verbose_thread.rb:38:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.17.1/lib/zold/endless.rb:45:in `block in run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.17.1/lib/zold/endless.rb:44:in `loop'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.17.1/lib/zold/endless.rb:44:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.17.1/lib/zold/node/farm.rb:126:in `block (2 levels) in start'
```

**Comment by dapi** [comment]
Even `openssl` leaks in ruby

```ruby
[1] pry(main)> a=GC.stat[:total_allocated_objects]                                                                                                                                   
=> 2603020
[2] pry(main)> GetProcessMem.new.bytes.to_i                                                                                                                                          
=> 114798592
[3] pry(main)> 10_000_000.times.each { OpenSSL::Digest::SHA256.new("asdflasdfskj").hexdigest }
=> 10000000
[4] pry(main)> GC.stat[:total_allocated_objects]-a                                                                                                                                   
=> 50005694
[5] pry(main)> GetProcessMem.new.bytes.to_i                                                                                                                                          
=> 132751360
```

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#590` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
