### ISSUE TITLE
Errno::ENOMEM: Cannot allocate memory - ps

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#615]
```
Errno::ENOMEM: Cannot allocate memory - ps
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.17.9/lib/zold/node/front.rb:467:in ``'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.17.9/lib/zold/node/front.rb:467:in `processes'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.17.9/lib/zold/node/front.rb:462:in `block in processes_count'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zache-0.4.0/lib/zache.rb:59:in `block (2 levels) in get'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zache-0.4.0/lib/zache.rb:117:in `calc'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zache-0.4.0/lib/zache.rb:59:in `block in get'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zache-0.4.0/lib/zache.rb:127:in `block in synchronized'
	/usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zache-0.4.0/lib/zache.rb:127:in `synchronized'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zache-0.4.0/lib/zache.rb:59:in `get'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.17.9/lib/zold/node/front.rb:461:in `processes_count'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.17.9/lib/zold/node/front.rb:202:in `block in <class:Front>'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
	/usr/local/rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/deflater.rb:34:in `call'
	/usr/local/rvm/gems/ruby-2.5.1/gems/rack-protection-2.0.4/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/rvm/gems/ruby-2.5.1/gems/rack-protection-2.0.4/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/rvm/gems/ruby-2.5.1/gems/rack-protection-2.0.4/lib/rack/protection/json_csrf.rb:26:in `call'
	/usr/local/rvm/gems/ruby-2.5.1/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	/usr/local/rvm/gems/ruby-2.5.1/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	/usr/local/rvm/gems/ruby-2.5.1/gems/rack-protection-2.0.4/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/null_logger.rb:9:in `call'
	/usr/local/rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call'
	/usr/local/rvm/gems/ruby-2.5.1/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/usr/local/rvm/gems/ruby-2.5.1/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/usr/local/rvm/gems/ruby-2.5.1/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/usr/local/rvm/gems/ruby-2.5.1/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'
	/usr/local/rvm/gems/ruby-2.5.1/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.10`

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.10`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#615` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
