### ISSUE TITLE
SoftError is not of type Exception

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#626]
```
TypeError: exception class/object expected
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.4/lib/zold/node/safe_entrance.rb:80:in `raise'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.4/lib/zold/node/safe_entrance.rb:80:in `block in push'
	/usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/tempfile.rb:295:in `open'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.4/lib/zold/node/safe_entrance.rb:63:in `push'
```

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#626](https://github.com/zold-io/zold/issues/626) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
