### ISSUE TITLE
Node stopped responding

### ISSUE THREAD

**Issue by emilianodellacasa** [zold-io/zold#634]
Agter a while that the node was up and running, suddenly it stopped responding.

This is the error that generated in the log:

```
Reconnected, there are 11 remote notes: 78.26.142.131:4096/0/0, 167.99.77.100:4096/7/2, b2.zold.io:4096/0/4, 159.65.198.8:4096/5/4, 138.201.231.23:4096/11/4, 84.194.34.107:4095/2/2, 138.197.140.42:4096/7/4, 159.203.63.90:4096/0/6, 159.203.19.189:4096/4/6, 68.183.21.200:4096/6/4, 84.194.34.107:4097/15/8
Nothing else left to read from #24449
Exit code of process #24449 is 9, was alive for 63h: /usr/local/bin/zold node --invoice=25e0819b40cf7eb6 --host 35.180.30.97
RuntimeError: Exit code is 9
        /var/lib/gems/2.5.0/gems/zold-0.18.7/lib/zold/commands/node.rb:338:in `block (2 levels) in nohup'
        /var/lib/gems/2.5.0/gems/zold-0.18.7/lib/zold/commands/node.rb:335:in `loop'
        /var/lib/gems/2.5.0/gems/zold-0.18.7/lib/zold/commands/node.rb:335:in `block in nohup'
        /var/lib/gems/2.5.0/gems/zold-0.18.7/lib/zold/commands/node.rb:323:in `fork'
        /var/lib/gems/2.5.0/gems/zold-0.18.7/lib/zold/commands/node.rb:323:in `nohup'
        /var/lib/gems/2.5.0/gems/zold-0.18.7/lib/zold/commands/node.rb:179:in `run'
        /var/lib/gems/2.5.0/gems/zold-0.18.7/lib/zold/commands/thread_badge.rb:41:in `run'
        /var/lib/gems/2.5.0/gems/zold-0.18.7/bin/zold:191:in `block in <top (required)>'
        /var/lib/gems/2.5.0/gems/zold-0.18.7/bin/zold:261:in `<top (required)>'
        /usr/local/bin/zold:23:in `load'
        /usr/local/bin/zold:23:in `<main>'Started process #32405 from process #12679: /usr/local/bin/zold node --invoice=25e0819b40cf7eb6 --host 35.180.30.97
Time: 2018-12-17T08:19:31Z; CPUs: 2
```

After a manual restart, it now works

**Comment by yegor256** [comment]
@emilianodellacasa  This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#634` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
