### ISSUE TITLE
at start "RuntimeError: Not enough lines"

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#635]
When node starts it can't get the invoice from the wallet:

```
Home directory: /root
Ruby version: 2.5.1/x86_64-linux
Zold gem version: 0.18.8
Zold protocol version: 2
Network ID: zold
Node location: 167.99.77.100:4096
Local address: http://127.0.0.1:4096/
Remote nodes (11): 84.194.34.107:4097, b2.zold.io:4096, 68.183.21.200:4096, 138.201.231.23:4096, 159.65.198.8:4096, 159.203.19.189:4096, 138.197.140.42:4096, 159.203.63.90:4096, b1.zold.io:80, 84.194.34.107:4095, 78.26.142.131:4096
Wallets at: /root
Not enough lines in /root/9/1/2/e/912ecc24b32dbe74.z, just 0 (RuntimeError)
RuntimeError: Not enough lines in /root/9/1/2/e/912ecc24b32dbe74.z, just 0
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.8/lib/zold/head.rb:43:in `fetch'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.8/lib/zold/head.rb:61:in `fetch'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.8/lib/zold/wallet.rb:175:in `key'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.8/lib/zold/prefixes.rb:40:in `create'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.8/lib/zold/commands/invoice.rb:74:in `block in invoice'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.8/lib/zold/sync_wallets.rb:61:in `block (2 levels) in acq'
	/usr/local/rvm/gems/ruby-2.5.1/gems/futex-0.7.0/lib/futex.rb:116:in `block in open'
	/usr/local/rvm/gems/ruby-2.5.1/gems/futex-0.7.0/lib/futex.rb:90:in `open'
	/usr/local/rvm/gems/ruby-2.5.1/gems/futex-0.7.0/lib/futex.rb:90:in `open'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.8/lib/zold/sync_wallets.rb:60:in `block in acq'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.8/lib/zold/cached_wallets.rb:65:in `block in acq'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.8/lib/zold/tree_wallets.rb:64:in `acq'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.8/lib/zold/cached_wallets.rb:63:in `acq'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.8/lib/zold/sync_wallets.rb:59:in `acq'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.8/lib/zold/commands/invoice.rb:73:in `invoice'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.8/lib/zold/commands/invoice.rb:61:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.8/lib/zold/commands/thread_badge.rb:41:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.8/lib/zold/commands/node.rb:235:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.8/lib/zold/commands/thread_badge.rb:41:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.8/bin/zold:191:in `block in <top (required)>'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.8/bin/zold:261:in `<top (required)>'
	/usr/local/rvm/gems/ruby-2.5.1/bin/zold:23:in `load'
	/usr/local/rvm/gems/ruby-2.5.1/bin/zold:23:in `<main>'
	/usr/local/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
	/usr/local/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.10`

**Comment by yegor256** [comment]
@rultor release, tag is `0.19.0`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#635` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
