### ISSUE TITLE
RuntimeError: You have to join at least one wallet in

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#636]
```
RuntimeError: You have to join at least one wallet in
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/patch.rb:118:in `save'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/commands/merge.rb:95:in `block in merge'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/sync_wallets.rb:47:in `block (2 levels) in acq'
	/usr/local/rvm/gems/ruby-2.5.1/gems/futex-0.7.0/lib/futex.rb:116:in `block in open'
	/usr/local/rvm/gems/ruby-2.5.1/gems/futex-0.7.0/lib/futex.rb:90:in `open'
	/usr/local/rvm/gems/ruby-2.5.1/gems/futex-0.7.0/lib/futex.rb:90:in `open'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/sync_wallets.rb:46:in `block in acq'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/cached_wallets.rb:51:in `block in acq'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/tree_wallets.rb:64:in `acq'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/cached_wallets.rb:49:in `acq'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/sync_wallets.rb:45:in `acq'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/commands/merge.rb:95:in `merge'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/commands/merge.rb:65:in `block in run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/commands/merge.rb:64:in `each'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/commands/merge.rb:64:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/commands/thread_badge.rb:41:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/commands/pull.rb:48:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/commands/thread_badge.rb:41:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/hungry_wallets.rb:48:in `block (2 levels) in initialize'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/endless.rb:45:in `block (2 levels) in run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/verbose_thread.rb:39:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/endless.rb:44:in `block in run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/endless.rb:43:in `loop'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/endless.rb:43:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/hungry_wallets.rb:46:in `block in initialize'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/thread_pool.rb:73:in `block (2 levels) in add'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/verbose_thread.rb:39:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.9/lib/zold/thread_pool.rb:71:in `block in add'
```

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#636` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
