### ISSUE TITLE
merge doesn't stop on failures in fetch

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#638]
```
RuntimeError: There are no remote nodes, run 'zold remote reset'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/commands/fetch.rb:104:in `fetch'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/commands/fetch.rb:86:in `block in run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/thread_pool.rb:55:in `block (3 levels) in run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/thread_pool.rb:52:in `loop'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/thread_pool.rb:52:in `block (2 levels) in run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/thread_pool.rb:73:in `block (2 levels) in add'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/verbose_thread.rb:39:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/thread_pool.rb:71:in `block in add'
RuntimeError: There are no copies of 053913b98c00fcb4, nothing to merge
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/commands/merge.rb:95:in `merge'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/commands/merge.rb:65:in `block in run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/commands/merge.rb:64:in `each'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/commands/merge.rb:64:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/commands/thread_badge.rb:41:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/commands/pull.rb:48:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/commands/thread_badge.rb:41:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/hungry_wallets.rb:48:in `block (2 levels) in initialize'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/endless.rb:45:in `block (2 levels) in run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/verbose_thread.rb:39:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/endless.rb:44:in `block in run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/endless.rb:43:in `loop'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/endless.rb:43:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/hungry_wallets.rb:46:in `block in initialize'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/thread_pool.rb:73:in `block (2 levels) in add'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/verbose_thread.rb:39:in `run'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.19.0/lib/zold/thread_pool.rb:71:in `block in add'
```

**Comment by 0crat** [comment]
The job [#638](https://github.com/zold-io/zold/issues/638) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/e268c247-fb90-4e0c-8a05-0673cdb0c6b5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#638` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
