### ISSUE TITLE
pay - convert zld to btc

### ISSUE THREAD

**Issue by blackout314** [zold-io/zold#644]
use case
i try to convert zld to btc from wts

steps to reproduce
1) login to wts
2) pull the wallet
3) try to convert 4 ZLD to BTC

errors in logs
```
ERROR: UserError: Payment amount can't be zero
	/app/objects/ops.rb:65:in `pay'
	/app/wts.rb:463:in `block (2 levels) in <top (required)>'
	/app/wts.rb:638:in `block in job'
	/app/objects/update_job.rb:47:in `call'
	/app/objects/clean_job.rb:39:in `call'
	/app/objects/versioned_job.rb:34:in `call'
	/app/objects/safe_job.rb:34:in `call'
	/app/objects/async_job.rb:46:in `block (2 levels) in call'
	/app/vendor/bundle/ruby/2.5.0/gems/futex-0.8.1/lib/futex.rb:124:in `block in open'
	/app/vendor/bundle/ruby/2.5.0/gems/futex-0.8.1/lib/futex.rb:98:in `open'
	/app/vendor/bundle/ruby/2.5.0/gems/futex-0.8.1/lib/futex.rb:98:in `open'
	/app/objects/async_job.rb:45:in `block in call'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

```
ERROR: TypeError: no implicit conversion of nil into String
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.20.0/lib/zold/commands/clean.rb:58:in `join'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.20.0/lib/zold/commands/clean.rb:58:in `block in run'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.20.0/lib/zold/commands/clean.rb:57:in `each'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.20.0/lib/zold/commands/clean.rb:57:in `run'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.20.0/lib/zold/commands/pull.rb:46:in `run'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.20.0/lib/zold/commands/thread_badge.rb:41:in `run'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.20.0/lib/zold/commands/invoice.rb:75:in `invoice'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.20.0/lib/zold/commands/invoice.rb:67:in `run'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.20.0/lib/zold/commands/thread_badge.rb:41:in `run'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.20.0/lib/zold/commands/pay.rb:79:in `run'
	/app/vendor/bundle/ruby/2.5.0/gems/zold-0.20.0/lib/zold/commands/thread_badge.rb:41:in `run'
	/app/objects/ops.rb:76:in `block in pay'
	/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/tempfile.rb:295:in `open'
	/app/objects/ops.rb:73:in `pay'
	/app/wts.rb:463:in `block (2 levels) in <top (required)>'
	/app/wts.rb:638:in `block in job'
	/app/objects/update_job.rb:47:in `call'
	/app/objects/clean_job.rb:39:in `call'
	/app/objects/versioned_job.rb:34:in `call'
	/app/objects/safe_job.rb:34:in `call'
	/app/objects/async_job.rb:46:in `block (2 levels) in call'
	/app/vendor/bundle/ruby/2.5.0/gems/futex-0.8.1/lib/futex.rb:124:in `block in open'
	/app/vendor/bundle/ruby/2.5.0/gems/futex-0.8.1/lib/futex.rb:98:in `open'
	/app/vendor/bundle/ruby/2.5.0/gems/futex-0.8.1/lib/futex.rb:98:in `open'
	/app/objects/async_job.rb:45:in `block in call'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

```
Wallet bf1cbb2017040c3c removed
138.197.140.42:4096 removed because of 9 errors (over 8)
84.194.34.107:4097 removed because of 10 errors (over 8)
159.65.198.8:4096 removed because of 10 errors (over 8)
84.194.34.107:4096 removed because of 10 errors (over 8)
84.194.34.107:4095 removed because of 10 errors (over 8)
The list of 14 remotes trimmed, 9 nodes left there
b1.zold.io:80: Service Unavailable (HTTP code 503, instead of 200) in 26ms
159.203.19.189:4096/5: the score is 0 (0.20.0) in 256ms
185.180.197.55:4096/6: the score is 6 (0.20.0) in 390ms
78.26.142.131:4096/9: the score is 51 (0.20.0) in 476ms
91.204.122.127:4096/0: the score is 13 (0.20.0) in 592ms
94.232.57.6:4096: Z0.3.0 is not a valid SemVer Version (http://semver.org) in 613ms
b2.zold.io:4096/2: the score is 79 (0.20.0) in 690ms
159.203.63.90:4096/3: the score is 1 (0.20.0) in 787ms
167.99.77.100:4096: Unexpected HTTP code 599, instead of 200 in 2.0s
138.197.140.42:4096: Unexpected HTTP code 599, instead of 200 in 2.0s
b1.zold.io:80: Service Unavailable (HTTP code 503, instead of 200) in 20ms
84.194.34.107:4097 added to the list, 11 total
159.65.198.8:4096 added to the list, 12 total
84.194.34.107:4095 added to the list, 13 total
94.232.57.6:4096: Z0.3.0 is not a valid SemVer Version (http://semver.org) in 812ms
159.65.198.8:4096 already exists among 13 others
84.194.34.107:4095 already exists among 13 others
138.201.231.23:4096 added to the list, 14 total
138.201.231.23:4096 already exists among 14 others
138.201.231.23:4096 already exists among 14 others
167.99.77.100:4096: Unexpected HTTP code 599, instead of 200 in 2.01s
138.197.140.42:4096: Unexpected HTTP code 599, instead of 200 in 2.0s
185.180.197.55:4096: The node 84.194.34.107:4096 is not responding, 599: in 2.53s
84.194.34.107:4096 added to the list, 15 total
b2.zold.io:4096/9: the score is 79 (0.20.0) in 2.71s
159.203.19.189:4096: The node 84.194.34.107:4096 is not responding, 599: in 2.73s
84.194.34.107:4096 already exists among 15 others
91.204.122.127:4096/0: the score is 13 (0.20.0) in 2.82s
84.194.34.107:4096 already exists among 15 others
159.203.63.90:4096/3: the score is 1 (0.20.0) in 2.84s
78.26.142.131:4096: The node 84.194.34.107:4096 is not responding, 599: in 2.89s
b1.zold.io:80: Service Unavailable (HTTP code 503, instead of 200) in 15ms
159.203.63.90:4096/3: the score is 1 (0.20.0) in 301ms
138.197.140.42:4096/8: the score is 3 (0.20.0) in 377ms
159.203.19.189:4096/5: the score is 0 (0.20.0) in 491ms
185.180.197.55:4096/6: the score is 6 (0.20.0) in 577ms
159.65.198.8:4096/10: the score is 8 (0.20.0) in 684ms
84.194.34.107:4096/13: the score is 30 (0.20.0) in 807ms
94.232.57.6:4096: Unexpected HTTP code 599, instead of 200 in 825ms
84.194.34.107:4095: Unexpected HTTP code 599, instead of 200 in 824ms
78.26.142.131:4096/1: the score is 51 (0.20.0) in 918ms
84.194.34.107:4097/9: the score is 25 (0.20.0) in 978ms
91.204.122.127:4096/0: the score is 13 (0.20.0) in 1.11s
b2.zold.io:4096/14: the score is 79 (0.20.0) in 1.15s
167.99.77.100:4096: Unexpected HTTP code 599, instead of 200 in 2.01s
138.201.231.23:4096: Unexpected HTTP code 599, instead of 200 in 2.01s
There are 15 known remotes with the overall score of 240, after update in 7.01s
16 remote nodes left in the list
b1.zold.io:80: Service Unavailable (HTTP code 503, instead of 200) in 10ms
138.197.140.42:4096/8 returned bf1cbb2017040c3c/120.2560/4t/4d8b46/1Kb 2h/2c as copy #1/2 in 262ms: 3 (0.20.0)
185.180.197.55:4096/6 returned bf1cbb2017040c3c/120.2560/4t/4d8b46/1Kb 25.16s/2c as copy #1/2 in 484ms: 6 (0.20.0)
84.194.34.107:4095/11 returned bf1cbb2017040c3c/120.2560/4t/4d8b46/1Kb 50.23s/2c as copy #1/2 in 535ms: 30 (0.20.0)
84.194.34.107:4097/9 returned bf1cbb2017040c3c/120.2560/4t/4d8b46/1Kb 2m/2c as copy #1/2 in 623ms: 25 (0.20.0)
94.232.57.6:4096/7 returned bf1cbb2017040c3c/128.2560/2t/678db7/606b ?/c as copy #2/2 in 771ms: 24 (Z0.3.0)
91.204.122.127:4096/1 returned bf1cbb2017040c3c/120.2560/4t/4d8b46/1Kb 5m/2c as copy #1/2 in 819ms: 13 (0.20.0)
159.65.198.8:4096/10 returned bf1cbb2017040c3c/120.2560/4t/4d8b46/1Kb 48.51s/1c as copy #1/2 in 848ms: 8 (0.20.0)
78.26.142.131:4096/0 returned bf1cbb2017040c3c/120.2560/4t/4d8b46/1Kb 5m/2c as copy #1/2 in 901ms: 51 (0.20.0)
159.203.19.189:4096/5 returned bf1cbb2017040c3c/120.2560/4t/4d8b46/1Kb 1m/1c as copy #1/2 in 927ms: 0 (0.20.0)
159.203.63.90:4096/3 returned bf1cbb2017040c3c/120.2560/4t/4d8b46/1Kb 37.63s/2c as copy #1/2 in 975ms: 1 (0.20.0)
84.194.34.107:4096/13 returned bf1cbb2017040c3c/120.2560/4t/4d8b46/1Kb 5m/2c as copy #1/2 in 1.03s: 30 (0.20.0)
b2.zold.io:4096/14 returned bf1cbb2017040c3c/120.2560/4t/4d8b46/1Kb 44.74s/2c as copy #1/2 in 1.05s: 79 (0.20.0)
167.99.77.100:4096: Unexpected HTTP code 599, instead of 200 in 2.0s
138.201.231.23:4096: Unexpected HTTP code 599, instead of 200 in 2.01s
12 copies of bf1cbb2017040c3c fetched in 2.04s with the total score of 270 from 15 nodes (4 master nodes)
2 copies with the total score of 279 successfully merged into bf1cbb2017040c3c/120.2560/4t/4d8b46/1Kb in 71ms
2018-12-19T06:26:59Z: Wallet bf1cbb2017040c3c pulled successfully in 2s
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@blackout314[/z](https://www.0crat.com/u/blackout314) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.1`

**Comment by yegor256** [comment]
@blackout314 it's fixed, thanks for reporting

**Comment by blackout314** [comment]
@yegor256 is a pleasure 👍

**Comment by blackout314** [comment]
wts still not working, but no errors

https://github.com/zold-io/wts.zold.io/issues/88
