### ISSUE TITLE
Errno::ENOMEM: Cannot allocate memory - find

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#646]
```
Routine Zold::Routines::Gc #0 failed in 2m
Errno::ENOMEM: Cannot allocate memory - find
	/root/zold/lib/zold/dir_items.rb:42:in ``'
	/root/zold/lib/zold/dir_items.rb:42:in `fetch'
	/root/zold/lib/zold/tree_wallets.rb:49:in `all'
	/usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/delegate.rb:83:in `method_missing'
	/usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/delegate.rb:83:in `method_missing'
	/root/zold/lib/zold/commands/routines/gc.rb:48:in `exec'
	/root/zold/lib/zold/metronome.rb:66:in `block (3 levels) in start'
	/root/zold/lib/zold/metronome.rb:63:in `loop'
	/root/zold/lib/zold/metronome.rb:63:in `block (2 levels) in start'
	/root/zold/lib/zold/thread_pool.rb:73:in `block (2 levels) in add'
	/root/zold/lib/zold/verbose_thread.rb:41:in `run'
	/root/zold/lib/zold/thread_pool.rb:71:in `block in add'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.2`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#646` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
