### ISSUE TITLE
Bandwidth consumption nodes seems high

### ISSUE THREAD

**Issue by ArnoStrouwen** [zold-io/zold#647]
What are normal ranges for download/upload of nodes?
My node used over 50 GB in 24 hours. Some of the output I saved (no idea if it is useful):
```
Can't hungry-pull 17737fee5b825835: There are only edge nodes, run 'zold remote update' or use --tolerate-edges
b1.zold.io:80: Temporary Redirect (HTTP code 307, instead of 200) in 202ms
b2.zold.io:4096: Temporary Redirect (HTTP code 307, instead of 200) in 87ms
159.203.63.90:4096: Temporary Redirect (HTTP code 307, instead of 200) in 191ms
84.194.34.107:4095/2: the score is 4 (0.20.1) in 380ms
159.203.19.189:4096: Temporary Redirect (HTTP code 307, instead of 200) in 215ms
84.194.34.107:4094/1: the score is 39 (0.20.1) in 501ms
138.197.140.42:4096: Temporary Redirect (HTTP code 307, instead of 200) in 216ms
167.99.77.100:4096: Temporary Redirect (HTTP code 307, instead of 200) in 383ms
84.194.34.107:4097/0: the score is 47 (0.20.1) in 1.11s
b1.zold.io:80: Temporary Redirect (HTTP code 307, instead of 200) in 200ms
84.194.34.107:4094/1: the score is 39 (0.20.1) in 404ms
b2.zold.io:4096: Temporary Redirect (HTTP code 307, instead of 200) in 92ms
84.194.34.107:4097/0: the score is 47 (0.20.1) in 601ms
159.203.63.90:4096: Temporary Redirect (HTTP code 307, instead of 200) in 127ms
159.203.19.189:4096: Temporary Redirect (HTTP code 307, instead of 200) in 124ms
138.197.140.42:4096: Temporary Redirect (HTTP code 307, instead of 200) in 212ms
167.99.77.100:4096: Temporary Redirect (HTTP code 307, instead of 200) in 312ms
84.194.34.107:4095/2: the score is 4 (0.20.1) in 795ms
84.194.34.107:4097/0: the score is 47 (0.20.1) in 389ms
b1.zold.io:80: Temporary Redirect (HTTP code 307, instead of 200) in 199ms
84.194.34.107:4094/1: the score is 39 (0.20.1) in 399ms
b2.zold.io:4096: Temporary Redirect (HTTP code 307, instead of 200) in 114ms
159.203.63.90:4096: Temporary Redirect (HTTP code 307, instead of 200) in 144ms
138.197.140.42:4096: Temporary Redirect (HTTP code 307, instead of 200) in 175ms
159.203.19.189:4096: Temporary Redirect (HTTP code 307, instead of 200) in 179ms
84.194.34.107:4095/2: the score is 4 (0.20.1) in 472ms
Slow response to GET http://84.194.34.107:4096/wallet/17737fee5b825835 from 192.168.0.1 in 1.59s
167.99.77.100:4096: Temporary Redirect (HTTP code 307, instead of 200) in 398ms
There are 9 known remotes with the overall score of 90, after update in 3.23s
The list of 9 remotes trimmed, 9 nodes left there
16 remote nodes left in the list
Reconnected, there are 9 remote notes: 84.194.34.107:4097/47/6, 138.197.140.42:4096/0/3, 159.203.19.189:4096/0/3, 167.99.77.100:4096/0/3, 159.203.63.90:4096/0/3, b2.zold.io:4096/0/3, b1.zold.io:80/0/3, 84.194.34.107:4095/4/3, 84.194.34.107:4094/39/7
b2.zold.io:4096: Temporary Redirect (HTTP code 307, instead of 200) in 74ms
b1.zold.io:80: Temporary Redirect (HTTP code 307, instead of 200) in 124ms
159.203.63.90:4096: Temporary Redirect (HTTP code 307, instead of 200) in 115ms
159.203.19.189:4096: Temporary Redirect (HTTP code 307, instead of 200) in 120ms
138.197.140.42:4096: Temporary Redirect (HTTP code 307, instead of 200) in 121ms
167.99.77.100:4096: Temporary Redirect (HTTP code 307, instead of 200) in 275ms
84.194.34.107:4097/8 returned 17737fee5b825835/17151.6114/5468t/0977da/2Mb 3m/3c as copy #62/5 in 4.15s: 47 (0.20.1)
84.194.34.107:4094/0 returned 17737fee5b825835/17151.6114/5468t/0977da/2Mb 3m/3c as copy #62/5 in 5.53s: 39 (0.20.1)
84.194.34.107:4095/1 returned 17737fee5b825835/17151.6114/5468t/0977da/2Mb 18m/3c as copy #62/5 in 5.93s: 4 (0.20.1)
Zold::Fetch::EdgesOnly: There are only edge nodes, run 'zold remote update' or use --tolerate-edges
	/var/lib/gems/2.5.0/gems/zold-0.20.1/lib/zold/commands/fetch.rb:117:in `fetch'
	/var/lib/gems/2.5.0/gems/zold-0.20.1/lib/zold/commands/fetch.rb:95:in `block in run'
	/var/lib/gems/2.5.0/gems/zold-0.20.1/lib/zold/thread_pool.rb:55:in `block (3 levels) in run'
	/var/lib/gems/2.5.0/gems/zold-0.20.1/lib/zold/thread_pool.rb:52:in `loop'
	/var/lib/gems/2.5.0/gems/zold-0.20.1/lib/zold/thread_pool.rb:52:in `block (2 levels) in run'
	/var/lib/gems/2.5.0/gems/zold-0.20.1/lib/zold/thread_pool.rb:73:in `block (2 levels) in add'
	/var/lib/gems/2.5.0/gems/zold-0.20.1/lib/zold/verbose_thread.rb:39:in `run'
	/var/lib/gems/2.5.0/gems/zold-0.20.1/lib/zold/thread_pool.rb:71:in `block in add'
Can't hungry-pull 17737fee5b825835: There are only edge nodes, run 'zold remote update' or use --tolerate-edges
Slow response to GET http://84.194.34.107:4096/wallet/17737fee5b825835 from 192.168.0.1 in 3.48s
b2.zold.io:4096: Temporary Redirect (HTTP code 307, instead of 200) in 48ms
159.203.63.90:4096: Temporary Redirect (HTTP code 307, instead of 200) in 121ms
b1.zold.io:80: Temporary Redirect (HTTP code 307, instead of 200) in 132ms
159.203.19.189:4096: Temporary Redirect (HTTP code 307, instead of 200) in 121ms
138.197.140.42:4096: Temporary Redirect (HTTP code 307, instead of 200) in 122ms
167.99.77.100:4096: Temporary Redirect (HTTP code 307, instead of 200) in 272ms
84.194.34.107:4097/8 returned 17737fee5b825835/17151.6114/5468t/0977da/2Mb 3m/3c as copy #62/5 in 3.97s: 47 (0.20.1)
84.194.34.107:4095/1 returned 17737fee5b825835/17151.6114/5468t/0977da/2Mb 18m/3c as copy #62/5 in 4.54s: 4 (0.20.1)
84.194.34.107:4094/0 returned 17737fee5b825835/17151.6114/5468t/0977da/2Mb 3m/3c as copy #62/5 in 5.95s: 39 (0.20.1)
```
And another
```
Nothing changed in 3be3416c805e4371 after merge of 3 copies
84.194.34.107:4096/10 returned 3be3416c805e4371/2127.6000/195t/85861d/17Kb 3m/3c as copy #1/3 in 121ms: 2 (0.20.1)
84.194.34.107:4095/8 returned 3be3416c805e4371/2127.6000/195t/85861d/17Kb 753ms/3c as copy #1/3 in 132ms: 4 (0.20.1)
159.65.198.8:4096/0 returned 3be3416c805e4371/2127.6000/195t/85861d/17Kb 1m/2c as copy #1/3 in 215ms: 4 (0.20.1)
5.196.248.39:4096/3 returned 3be3416c805e4371/2127.6000/195t/85861d/17Kb 5m/2c as copy #1/3 in 332ms: 5 (0.20.1)
84.194.34.107:4094/15 returned 3be3416c805e4371/2127.6000/195t/85861d/17Kb 1.89s/3c as copy #1/3 in 171ms: 39 (0.20.1)
138.201.231.23:4096/11 returned 3be3416c805e4371/2127.6000/195t/85861d/17Kb 6m/3c as copy #1/3 in 358ms: 4 (0.20.1)
95.142.46.132:4096/5 returned 3be3416c805e4371/2127.6000/195t/85861d/17Kb 6m/2c as copy #1/3 in 422ms: 16 (0.20.1)
91.204.122.125:4096/9 returned 3be3416c805e4371/2127.6000/195t/85861d/17Kb 6m/2c as copy #1/3 in 419ms: 8 (0.20.1)
185.180.197.55:4096/1 returned 3be3416c805e4371/2127.6000/195t/85861d/17Kb 23.05s/2c as copy #1/3 in 477ms: 4 (0.20.1)
91.204.122.127:4096/14 returned 3be3416c805e4371/2127.6000/195t/85861d/17Kb 1m/3c as copy #1/3 in 321ms: 10 (0.20.1)
159.203.19.189:4096/7 returned 3be3416c805e4371/2127.6000/195t/85861d/17Kb 5.15s/1c as copy #1/3 in 541ms: 2 (0.20.1)
159.203.63.90:4096/6 returned 3be3416c805e4371/2127.6000/195t/85861d/17Kb 16.15s/2c as copy #1/3 in 546ms: 5 (0.20.1)
94.232.57.6:4096/2 returned 3be3416c805e4371/2177.2800/199t/bc91a1/15Kb ?/c as copy #2/3 in 784ms: 20 (Z0.3.0)
51.254.111.163:4096/12 returned 3be3416c805e4371/2127.6000/195t/85861d/17Kb 10.55s/2c as copy #1/3 in 908ms: 14 (0.20.1)
35.180.30.97:4096/13 returned 3be3416c805e4371/2127.6000/195t/85861d/17Kb 14h/2c as copy #1/3 in 1.01s: 4 (0.20.1)
167.99.77.100:4096/4 returned 3be3416c805e4371/2127.6000/195t/85861d/17Kb 8m/2c as copy #1/3 in 1.22s: 7 (0.20.1)
16 copies of 3be3416c805e4371 fetched in 1.26s with the total score of 148 from 16 nodes (3 master nodes)
Payment prefix 'EMsk0kMk' doesn't match with the key of 3be3416c805e4371: "- 2018-07-02T10:32:12Z 8.00ZLD 17737fee5b825835 WTS signup bonus to g4s8"
Payment prefix '03eDDQGp' doesn't match with the key of 3be3416c805e4371: "- 2018-07-03T12:47:30Z 2.67ZLD 17737fee5b825835 none"
Payment prefix '03eDDQGp' doesn't match with the key of 3be3416c805e4371: "- 2018-07-03T13:19:48Z 8.00ZLD 17737fee5b825835 none"
Payment prefix 'IihagWrg' doesn't match with the key of 3be3416c805e4371: "- 2018-07-03T13:21:11Z 8.00ZLD 17737fee5b825835 none"
Payment prefix 'JAhjN7aY' doesn't match with the key of 3be3416c805e4371: "- 2018-07-03T17:43:06Z 2.00ZLD 17737fee5b825835 none"
Payment prefix 'IihagWrg' doesn't match with the key of 3be3416c805e4371: "- 2018-07-04T10:31:08Z 2.67ZLD 17737fee5b825835 none"
Payment prefix 'ZrIihagW' doesn't match with the key of 3be3416c805e4371: "- 2018-07-04T13:11:36Z 2.67ZLD 17737fee5b825835 none"
Payment prefix 'IihagWrg' doesn't match with the key of 3be3416c805e4371: "- 2018-07-04T14:49:28Z 2.67ZLD 17737fee5b825835 none"
Payment prefix 'EMsk0kMk' doesn't match with the key of 3be3416c805e4371: "- 2018-07-02T10:32:12Z 8.00ZLD 17737fee5b825835 WTS signup bonus to g4s8"
Payment prefix '03eDDQGp' doesn't match with the key of 3be3416c805e4371: "- 2018-07-03T12:47:30Z 2.67ZLD 17737fee5b825835 none"
Payment prefix '03eDDQGp' doesn't match with the key of 3be3416c805e4371: "- 2018-07-03T13:19:48Z 8.00ZLD 17737fee5b825835 none"
Payment prefix 'IihagWrg' doesn't match with the key of 3be3416c805e4371: "- 2018-07-03T13:21:11Z 8.00ZLD 17737fee5b825835 none"
Payment prefix 'JAhjN7aY' doesn't match with the key of 3be3416c805e4371: "- 2018-07-03T17:43:06Z 2.00ZLD 17737fee5b825835 none"
Payment prefix 'IihagWrg' doesn't match with the key of 3be3416c805e4371: "- 2018-07-04T10:31:08Z 2.67ZLD 17737fee5b825835 none"
Payment prefix 'ZrIihagW' doesn't match with the key of 3be3416c805e4371: "- 2018-07-04T13:11:36Z 2.67ZLD 17737fee5b825835 none"
Payment prefix 'IihagWrg' doesn't match with the key of 3be3416c805e4371: "- 2018-07-04T14:49:28Z 2.67ZLD 17737fee5b825835 none"
Nothing changed in 3be3416c805e4371 after merge of 3 copies
```
Most days the consumption is far less (5 to 10GB). Even this seems very high and is discouraging me to run a node.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ArnoJL it's a known problem, thanks for reporting, we will fix it ASAP.

**Comment by 0crat** [comment]
Job [#647](https://github.com/zold-io/zold/issues/647) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Thanks for your contribution, @arnojl[/z](https://www.0crat.com/u/arnojl)! If you would be a member of [the project](https://www.0crat.com/p/CAZPZR9FS), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by yegor256** [comment]
@ArnoStrouwen this may help: https://github.com/zold-io/zold/issues/665 Let's see what happens after we release it

**Comment by yegor256** [comment]
@ArnoStrouwen This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#647` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#647](https://github.com/zold-io/zold/issues/647) is now out of scope
