### ISSUE TITLE
Version 0.21.2 doesn't work with error `require': cannot load such file -- parallel (LoadError)

### ISSUE THREAD

**Issue by stepan-romankov** [zold-io/zold#664]
`zold node --invoice=4e1c0b133e8141a4 --threads=8 --network=zold`

Logs:

```
zold_1  | /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in 'require': cannot load such file -- parallel (LoadError)
zold_1  | 	from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
zold_1  | 	from /usr/local/bundle/gems/zold-0.21.2/lib/zold/commands/fetch.rb:32:in '<top (required)>'
zold_1  | 	from /usr/local/bundle/gems/zold-0.21.2/lib/zold/commands/pull.rb:25:in 'require_relative'
zold_1  | 	from /usr/local/bundle/gems/zold-0.21.2/lib/zold/commands/pull.rb:25:in '<top (required)>'
zold_1  | 	from /usr/local/bundle/gems/zold-0.21.2/lib/zold/hungry_wallets.rb:26:in 'require_relative'
zold_1  | 	from /usr/local/bundle/gems/zold-0.21.2/lib/zold/hungry_wallets.rb:26:in '<top (required)>'
zold_1  | 	from /usr/local/bundle/gems/zold-0.21.2/bin/zold:41:in 'require_relative'
zold_1  | 	from /usr/local/bundle/gems/zold-0.21.2/bin/zold:41:in '<top (required)>'
zold_1  | 	from /usr/local/bundle/bin/zold:23:in 'load'
zold_1  | 	from /usr/local/bundle/bin/zold:23:in '<main>'
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@stepan-romankov[/z](https://www.0crat.com/u/stepan-romankov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.3`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.3`

**Comment by yegor256** [comment]
@stepan-romankov should be fine now, please try and close the ticket

**Comment by stepan-romankov** [comment]
Works now! Thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#664` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
