### ISSUE TITLE
NoMethodError: undefined method `error' for nil:NilClass

### ISSUE THREAD

**Issue by denis-konovalyenko** [zold-io/zold#677]
On requesting the http://91.211.13.180:4096/ resource the following error occurs:
```
NoMethodError: undefined method `error' for nil:NilClass
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/zold-0.22.3/lib/zold/node/front.rb:457:in `rescue in block in total_mem'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/zold-0.22.3/lib/zold/node/front.rb:455:in `block in total_mem'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/zache-0.11.0/lib/zache.rb:102:in `block (2 levels) in get'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/zache-0.11.0/lib/zache.rb:180:in `calc'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/zache-0.11.0/lib/zache.rb:102:in `block in get'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/zache-0.11.0/lib/zache.rb:195:in `block in synchronized'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/zache-0.11.0/lib/zache.rb:190:in `synchronize'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/zache-0.11.0/lib/zache.rb:190:in `synchronized'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/zache-0.11.0/lib/zache.rb:102:in `get'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/zold-0.22.3/lib/zold/node/front.rb:454:in `total_mem'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/zold-0.22.3/lib/zold/node/front.rb:227:in `block in <class:Front>'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/rack-2.0.6/lib/rack/deflater.rb:34:in `call'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/rack-protection-2.0.4/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/rack-protection-2.0.4/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/rack-protection-2.0.4/lib/rack/protection/json_csrf.rb:26:in `call'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/rack-protection-2.0.4/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/rack-2.0.6/lib/rack/logger.rb:15:in `call'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/rack-2.0.6/lib/rack/common_logger.rb:33:in `call'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:231:in `call'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:224:in `call'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'
	/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'
```
My system is:
```
FreeBSD dmz1 11.2-RELEASE-p5 FreeBSD 11.2-RELEASE-p5 #0: Tue Nov 27 17:06:40 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  i386
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#677` is not assigned, can't get performer
