### ISSUE TITLE
typo in push.rb

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#680]
```
NoMethodError: undefined method `+' for nil:NilClass
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.4/lib/zold/commands/push.rb:163:in `rescue in read_one'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.4/lib/zold/commands/push.rb:149:in `read_one'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.4/lib/zold/commands/push.rb:134:in `push_one'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.4/lib/zold/commands/push.rb:108:in `block in push'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.4/lib/zold/remotes.rb:197:in `block in iterate'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.4/lib/zold/hands.rb:88:in `block (3 levels) in exec'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.4/lib/zold/hands.rb:85:in `loop'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.4/lib/zold/hands.rb:85:in `block (2 levels) in exec'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.4/lib/zold/hands.rb:56:in `block (2 levels) in start'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.4/lib/zold/endless.rb:45:in `block (2 levels) in run'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.4/lib/zold/verbose_thread.rb:41:in `run'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.4/lib/zold/endless.rb:44:in `block in run'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.4/lib/zold/endless.rb:43:in `loop'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.4/lib/zold/endless.rb:43:in `run'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.4/lib/zold/hands.rb:55:in `block in start'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.4/lib/zold/thread_pool.rb:49:in `block (2 levels) in add'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.4/lib/zold/verbose_thread.rb:41:in `run'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.4/lib/zold/thread_pool.rb:47:in `block in add'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.5`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#680` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
