### ISSUE TITLE
NoMethodError: undefined method `root?' for Zold::Id

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#681]
```
NoMethodError: undefined method `root?' for #<Zold::Id:0x0000000004ad6958 @id=16552413578365767383>
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/signature.rb:59:in `valid?'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/patch.rb:93:in `block in join'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/patch.rb:77:in `each'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/patch.rb:77:in `join'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/commands/merge.rb:131:in `merge_one'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/commands/merge.rb:105:in `block in merge'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/commands/merge.rb:102:in `each'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/commands/merge.rb:102:in `each_with_index'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/commands/merge.rb:102:in `merge'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/commands/merge.rb:77:in `block in run'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/commands/merge.rb:76:in `each'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/commands/merge.rb:76:in `run'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/commands/thread_badge.rb:41:in `run'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/commands/pull.rb:48:in `run'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/commands/thread_badge.rb:41:in `run'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/hungry_wallets.rb:78:in `pull'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/hungry_wallets.rb:48:in `block (2 levels) in initialize'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/endless.rb:45:in `block (2 levels) in run'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/verbose_thread.rb:41:in `run'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/endless.rb:44:in `block in run'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/endless.rb:43:in `loop'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/endless.rb:43:in `run'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/hungry_wallets.rb:48:in `block in initialize'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/thread_pool.rb:49:in `block (2 levels) in add'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/verbose_thread.rb:41:in `run'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.22.5/lib/zold/thread_pool.rb:47:in `block in add'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.6`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#681` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
