### ISSUE TITLE
wrong transaction details (broken regex?)

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#692]
```
RuntimeError: Wrong details "ZLD exchange to 0.00104 BTC at 3NimQKG2kuseH3cg­6z3hdbdEHbqai9kQ­Hj, rate is 0.00026, fee is 0.08" ([a-zA-Z0-9 @\!\?\*_\-\.:,'/]+)
  from zold/txn.rb:91:in `initialize'
  from zold/wallet.rb:145:in `new'
  from zold/wallet.rb:145:in `sub'
  from zold/commands/pay.rb:127:in `pay'
  from zold/commands/pay.rb:97:in `block in run'
```

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#692` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
