### ISSUE TITLE
NoMethodError: undefined method `mtime' for #<Zache:0x00000000027ec6e0>

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#701]
```
NoMethodError: undefined method `mtime' for #<Zache:0x00000000027ec6e0>
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.23.3/lib/zold/hungry_wallets.rb:61:in `block in acq'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.23.3/lib/zold/sync_wallets.rb:47:in `block (2 levels) in acq'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/futex-0.8.5/lib/futex.rb:129:in `block in open'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/futex-0.8.5/lib/futex.rb:175:in `open_synchronized'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/futex-0.8.5/lib/futex.rb:103:in `open'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.23.3/lib/zold/sync_wallets.rb:46:in `block in acq'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.23.3/lib/zold/cached_wallets.rb:51:in `block in acq'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.23.3/lib/zold/tree_wallets.rb:64:in `acq'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.23.3/lib/zold/cached_wallets.rb:49:in `acq'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.23.3/lib/zold/sync_wallets.rb:45:in `acq'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.23.3/lib/zold/hungry_wallets.rb:56:in `acq'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.23.3/lib/zold/node/front.rb:501:in `fetch'
	/home/yegor/.rvm/gems/ruby-2.5.1/gems/zold-0.23.3/lib/zold/node/front.rb:262:in `block in <class:Front>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.23.4`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#701` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
