### ISSUE TITLE
NoMethodError: undefined method `>' for nil:NilClass

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#725]
```
NoMethodError: undefined method `>' for nil:NilClass
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.24.5/lib/zold/node/front.rb:543:in `block in add_new_remote'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.24.5/lib/zold/node/front.rb:543:in `each'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.24.5/lib/zold/node/front.rb:543:in `none?'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.24.5/lib/zold/node/front.rb:543:in `add_new_remote'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.24.5/lib/zold/node/front.rb:121:in `block (2 levels) in <class:Front>'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.24.5/lib/zold/node/front.rb:479:in `check_header'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.24.5/lib/zold/node/front.rb:109:in `block in <class:Front>'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:983:in `block in filter!'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:983:in `each'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:983:in `filter!'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1096:in `block in dispatch!'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/usr/local/rvm/gems/ruby-2.5.1/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.24.6`

**Comment by yegor256** [comment]
@rultor release, tag is `0.24.6`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#725` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
