### ISSUE TITLE
Cannot access zold wallet - Internal error at 0.35.31

### ISSUE THREAD

**Issue by shuhikari** [zold-io/zold#767]
**Describe the bug**
Cannot access my zold wallet through [wts.zold.io](http://wts.zold.io)

**To Reproduce**
1. Try to open [wts.zold.io](http://wts.zold.io)
2. Then, click on login
3. Login with github

**Expected behavior**
The website should open normally and show the wallet's info

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14.3 64-bit
 - Browser: Opera
 - Version: 60.0.3255.170

**Additional context**

The website says: 

Internal error at 0.35.31

Please help us improve our service and submit the following stacktrace to our GitHub repo :

PG::UnableToSend: no connection to the server

	/app/vendor/bundle/ruby/2.6.0/gems/pgtk-0.6.2/lib/pgtk/pool.rb:165:in `async_exec_params'
	/app/vendor/bundle/ruby/2.6.0/gems/pgtk-0.6.2/lib/pgtk/pool.rb:165:in `exec'
	/app/vendor/bundle/ruby/2.6.0/gems/pgtk-0.6.2/lib/pgtk/pool.rb:135:in `block in exec'
	/app/vendor/bundle/ruby/2.6.0/gems/pgtk-0.6.2/lib/pgtk/pool.rb:184:in `connect'
	/app/vendor/bundle/ruby/2.6.0/gems/pgtk-0.6.2/lib/pgtk/pool.rb:128:in `exec'
	/app/objects/toggles.rb:50:in `get'
	/app/wts.rb:386:in `rate'
	/app/views/index.haml:28:in `block in singleton class'
	/app/views/index.haml:-13:in `instance_eval'
	/app/views/index.haml:-13:in `singleton class'
	/app/views/index.haml:-16:in `__tilt_11041120'
	/app/vendor/bundle/ruby/2.6.0/gems/tilt-2.0.9/lib/tilt/template.rb:170:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/tilt-2.0.9/lib/tilt/template.rb:170:in `evaluate'
	/app/vendor/bundle/ruby/2.6.0/gems/tilt-2.0.9/lib/tilt/haml.rb:24:in `evaluate'
	/app/vendor/bundle/ruby/2.6.0/gems/tilt-2.0.9/lib/tilt/template.rb:109:in `render'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:839:in `render'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:692:in `haml'
	/app/wts.rb:202:in `block in <top (required)>'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `block in compile!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1011:in `route_eval'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1040:in `block in process_route'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `process_route'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:990:in `block in route!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `each'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `route!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1094:in `dispatch!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `block in call!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `call!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:913:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack_csrf-2.6.0/lib/rack/csrf.rb:38:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:232:in `context'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-ssl-1.4.1/lib/rack/ssl.rb:27:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/xss_header.rb:18:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/path_traversal.rb:16:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/json_csrf.rb:26:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/frame_options.rb:31:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/logger.rb:15:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/common_logger.rb:33:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:231:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:224:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:194:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1957:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `block in call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1729:in `synchronize'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	/app/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	/app/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/handler/thin.rb:22:in `run'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:297:in `start'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:148:in `start'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/bin/rackup:4:in `<top (required)>'
	/app/vendor/bundle/ruby/2.6.0/bin/rackup:23:in `load'
	/app/vendor/bundle/ruby/2.6.0/bin/rackup:23:in `<top (required)>'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
	/app/vendor/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	/app/vendor/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
	/app/vendor/bundle/bin/bundle:104:in `load'
	/app/vendor/bundle/bin/bundle:104:in `<main>'

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@shuhikari[/z](https://www.0crat.com/u/shuhikari) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!
